// Code generated by ent, DO NOT EDIT.

package auditstreamcursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldContainsFold(FieldID, id))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastID applies equality check predicate on the "last_id" field. It's identical to LastIDEQ.
func LastID(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEQ(FieldLastID, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastIDEQ applies the EQ predicate on the "last_id" field.
func LastIDEQ(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEQ(FieldLastID, v))
}

// LastIDNEQ applies the NEQ predicate on the "last_id" field.
func LastIDNEQ(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldNEQ(FieldLastID, v))
}

// LastIDIn applies the In predicate on the "last_id" field.
func LastIDIn(vs ...string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldIn(FieldLastID, vs...))
}

// LastIDNotIn applies the NotIn predicate on the "last_id" field.
func LastIDNotIn(vs ...string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldNotIn(FieldLastID, vs...))
}

// LastIDGT applies the GT predicate on the "last_id" field.
func LastIDGT(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldGT(FieldLastID, v))
}

// LastIDGTE applies the GTE predicate on the "last_id" field.
func LastIDGTE(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldGTE(FieldLastID, v))
}

// LastIDLT applies the LT predicate on the "last_id" field.
func LastIDLT(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldLT(FieldLastID, v))
}

// LastIDLTE applies the LTE predicate on the "last_id" field.
func LastIDLTE(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldLTE(FieldLastID, v))
}

// LastIDContains applies the Contains predicate on the "last_id" field.
func LastIDContains(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldContains(FieldLastID, v))
}

// LastIDHasPrefix applies the HasPrefix predicate on the "last_id" field.
func LastIDHasPrefix(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldHasPrefix(FieldLastID, v))
}

// LastIDHasSuffix applies the HasSuffix predicate on the "last_id" field.
func LastIDHasSuffix(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldHasSuffix(FieldLastID, v))
}

// LastIDIsNil applies the IsNil predicate on the "last_id" field.
func LastIDIsNil() predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldIsNull(FieldLastID))
}

// LastIDNotNil applies the NotNil predicate on the "last_id" field.
func LastIDNotNil() predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldNotNull(FieldLastID))
}

// LastIDEqualFold applies the EqualFold predicate on the "last_id" field.
func LastIDEqualFold(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldEqualFold(FieldLastID, v))
}

// LastIDContainsFold applies the ContainsFold predicate on the "last_id" field.
func LastIDContainsFold(v string) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.FieldContainsFold(FieldLastID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditStreamCursor) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditStreamCursor) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditStreamCursor) predicate.AuditStreamCursor {
	return predicate.AuditStreamCursor(sql.NotPredicates(p))
}
