// Code generated by ent, DO NOT EDIT.

package session

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// AgentSessionID applies equality check predicate on the "agent_session_id" field. It's identical to AgentSessionIDEQ.
func AgentSessionID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentSessionID, v))
}

// AgentName applies equality check predicate on the "agent_name" field. It's identical to AgentNameEQ.
func AgentName(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentName, v))
}

// AgentVersion applies equality check predicate on the "agent_version" field. It's identical to AgentVersionEQ.
func AgentVersion(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentVersion, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEndedAt, v))
}

// WorkingDirectory applies equality check predicate on the "working_directory" field. It's identical to WorkingDirectoryEQ.
func WorkingDirectory(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldWorkingDirectory, v))
}

// ProjectName applies equality check predicate on the "project_name" field. It's identical to ProjectNameEQ.
func ProjectName(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProjectName, v))
}

// TotalActions applies equality check predicate on the "total_actions" field. It's identical to TotalActionsEQ.
func TotalActions(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTotalActions, v))
}

// FilesRead applies equality check predicate on the "files_read" field. It's identical to FilesReadEQ.
func FilesRead(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFilesRead, v))
}

// FilesWritten applies equality check predicate on the "files_written" field. It's identical to FilesWrittenEQ.
func FilesWritten(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFilesWritten, v))
}

// CommandsExecuted applies equality check predicate on the "commands_executed" field. It's identical to CommandsExecutedEQ.
func CommandsExecuted(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCommandsExecuted, v))
}

// Errors applies equality check predicate on the "errors" field. It's identical to ErrorsEQ.
func Errors(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldErrors, v))
}

// AgentSessionIDEQ applies the EQ predicate on the "agent_session_id" field.
func AgentSessionIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentSessionID, v))
}

// AgentSessionIDNEQ applies the NEQ predicate on the "agent_session_id" field.
func AgentSessionIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldAgentSessionID, v))
}

// AgentSessionIDIn applies the In predicate on the "agent_session_id" field.
func AgentSessionIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldAgentSessionID, vs...))
}

// AgentSessionIDNotIn applies the NotIn predicate on the "agent_session_id" field.
func AgentSessionIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldAgentSessionID, vs...))
}

// AgentSessionIDGT applies the GT predicate on the "agent_session_id" field.
func AgentSessionIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldAgentSessionID, v))
}

// AgentSessionIDGTE applies the GTE predicate on the "agent_session_id" field.
func AgentSessionIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldAgentSessionID, v))
}

// AgentSessionIDLT applies the LT predicate on the "agent_session_id" field.
func AgentSessionIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldAgentSessionID, v))
}

// AgentSessionIDLTE applies the LTE predicate on the "agent_session_id" field.
func AgentSessionIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldAgentSessionID, v))
}

// AgentSessionIDContains applies the Contains predicate on the "agent_session_id" field.
func AgentSessionIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldAgentSessionID, v))
}

// AgentSessionIDHasPrefix applies the HasPrefix predicate on the "agent_session_id" field.
func AgentSessionIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldAgentSessionID, v))
}

// AgentSessionIDHasSuffix applies the HasSuffix predicate on the "agent_session_id" field.
func AgentSessionIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldAgentSessionID, v))
}

// AgentSessionIDIsNil applies the IsNil predicate on the "agent_session_id" field.
func AgentSessionIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldAgentSessionID))
}

// AgentSessionIDNotNil applies the NotNil predicate on the "agent_session_id" field.
func AgentSessionIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldAgentSessionID))
}

// AgentSessionIDEqualFold applies the EqualFold predicate on the "agent_session_id" field.
func AgentSessionIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldAgentSessionID, v))
}

// AgentSessionIDContainsFold applies the ContainsFold predicate on the "agent_session_id" field.
func AgentSessionIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldAgentSessionID, v))
}

// AgentNameEQ applies the EQ predicate on the "agent_name" field.
func AgentNameEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentName, v))
}

// AgentNameNEQ applies the NEQ predicate on the "agent_name" field.
func AgentNameNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldAgentName, v))
}

// AgentNameIn applies the In predicate on the "agent_name" field.
func AgentNameIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldAgentName, vs...))
}

// AgentNameNotIn applies the NotIn predicate on the "agent_name" field.
func AgentNameNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldAgentName, vs...))
}

// AgentNameGT applies the GT predicate on the "agent_name" field.
func AgentNameGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldAgentName, v))
}

// AgentNameGTE applies the GTE predicate on the "agent_name" field.
func AgentNameGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldAgentName, v))
}

// AgentNameLT applies the LT predicate on the "agent_name" field.
func AgentNameLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldAgentName, v))
}

// AgentNameLTE applies the LTE predicate on the "agent_name" field.
func AgentNameLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldAgentName, v))
}

// AgentNameContains applies the Contains predicate on the "agent_name" field.
func AgentNameContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldAgentName, v))
}

// AgentNameHasPrefix applies the HasPrefix predicate on the "agent_name" field.
func AgentNameHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldAgentName, v))
}

// AgentNameHasSuffix applies the HasSuffix predicate on the "agent_name" field.
func AgentNameHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldAgentName, v))
}

// AgentNameEqualFold applies the EqualFold predicate on the "agent_name" field.
func AgentNameEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldAgentName, v))
}

// AgentNameContainsFold applies the ContainsFold predicate on the "agent_name" field.
func AgentNameContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldAgentName, v))
}

// AgentVersionEQ applies the EQ predicate on the "agent_version" field.
func AgentVersionEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldAgentVersion, v))
}

// AgentVersionNEQ applies the NEQ predicate on the "agent_version" field.
func AgentVersionNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldAgentVersion, v))
}

// AgentVersionIn applies the In predicate on the "agent_version" field.
func AgentVersionIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldAgentVersion, vs...))
}

// AgentVersionNotIn applies the NotIn predicate on the "agent_version" field.
func AgentVersionNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldAgentVersion, vs...))
}

// AgentVersionGT applies the GT predicate on the "agent_version" field.
func AgentVersionGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldAgentVersion, v))
}

// AgentVersionGTE applies the GTE predicate on the "agent_version" field.
func AgentVersionGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldAgentVersion, v))
}

// AgentVersionLT applies the LT predicate on the "agent_version" field.
func AgentVersionLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldAgentVersion, v))
}

// AgentVersionLTE applies the LTE predicate on the "agent_version" field.
func AgentVersionLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldAgentVersion, v))
}

// AgentVersionContains applies the Contains predicate on the "agent_version" field.
func AgentVersionContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldAgentVersion, v))
}

// AgentVersionHasPrefix applies the HasPrefix predicate on the "agent_version" field.
func AgentVersionHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldAgentVersion, v))
}

// AgentVersionHasSuffix applies the HasSuffix predicate on the "agent_version" field.
func AgentVersionHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldAgentVersion, v))
}

// AgentVersionIsNil applies the IsNil predicate on the "agent_version" field.
func AgentVersionIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldAgentVersion))
}

// AgentVersionNotNil applies the NotNil predicate on the "agent_version" field.
func AgentVersionNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldAgentVersion))
}

// AgentVersionEqualFold applies the EqualFold predicate on the "agent_version" field.
func AgentVersionEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldAgentVersion, v))
}

// AgentVersionContainsFold applies the ContainsFold predicate on the "agent_version" field.
func AgentVersionContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldAgentVersion, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldEndedAt))
}

// WorkingDirectoryEQ applies the EQ predicate on the "working_directory" field.
func WorkingDirectoryEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldWorkingDirectory, v))
}

// WorkingDirectoryNEQ applies the NEQ predicate on the "working_directory" field.
func WorkingDirectoryNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldWorkingDirectory, v))
}

// WorkingDirectoryIn applies the In predicate on the "working_directory" field.
func WorkingDirectoryIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldWorkingDirectory, vs...))
}

// WorkingDirectoryNotIn applies the NotIn predicate on the "working_directory" field.
func WorkingDirectoryNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldWorkingDirectory, vs...))
}

// WorkingDirectoryGT applies the GT predicate on the "working_directory" field.
func WorkingDirectoryGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldWorkingDirectory, v))
}

// WorkingDirectoryGTE applies the GTE predicate on the "working_directory" field.
func WorkingDirectoryGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldWorkingDirectory, v))
}

// WorkingDirectoryLT applies the LT predicate on the "working_directory" field.
func WorkingDirectoryLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldWorkingDirectory, v))
}

// WorkingDirectoryLTE applies the LTE predicate on the "working_directory" field.
func WorkingDirectoryLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldWorkingDirectory, v))
}

// WorkingDirectoryContains applies the Contains predicate on the "working_directory" field.
func WorkingDirectoryContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldWorkingDirectory, v))
}

// WorkingDirectoryHasPrefix applies the HasPrefix predicate on the "working_directory" field.
func WorkingDirectoryHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldWorkingDirectory, v))
}

// WorkingDirectoryHasSuffix applies the HasSuffix predicate on the "working_directory" field.
func WorkingDirectoryHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldWorkingDirectory, v))
}

// WorkingDirectoryIsNil applies the IsNil predicate on the "working_directory" field.
func WorkingDirectoryIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldWorkingDirectory))
}

// WorkingDirectoryNotNil applies the NotNil predicate on the "working_directory" field.
func WorkingDirectoryNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldWorkingDirectory))
}

// WorkingDirectoryEqualFold applies the EqualFold predicate on the "working_directory" field.
func WorkingDirectoryEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldWorkingDirectory, v))
}

// WorkingDirectoryContainsFold applies the ContainsFold predicate on the "working_directory" field.
func WorkingDirectoryContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldWorkingDirectory, v))
}

// ProjectNameEQ applies the EQ predicate on the "project_name" field.
func ProjectNameEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProjectName, v))
}

// ProjectNameNEQ applies the NEQ predicate on the "project_name" field.
func ProjectNameNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldProjectName, v))
}

// ProjectNameIn applies the In predicate on the "project_name" field.
func ProjectNameIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldProjectName, vs...))
}

// ProjectNameNotIn applies the NotIn predicate on the "project_name" field.
func ProjectNameNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldProjectName, vs...))
}

// ProjectNameGT applies the GT predicate on the "project_name" field.
func ProjectNameGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldProjectName, v))
}

// ProjectNameGTE applies the GTE predicate on the "project_name" field.
func ProjectNameGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldProjectName, v))
}

// ProjectNameLT applies the LT predicate on the "project_name" field.
func ProjectNameLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldProjectName, v))
}

// ProjectNameLTE applies the LTE predicate on the "project_name" field.
func ProjectNameLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldProjectName, v))
}

// ProjectNameContains applies the Contains predicate on the "project_name" field.
func ProjectNameContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldProjectName, v))
}

// ProjectNameHasPrefix applies the HasPrefix predicate on the "project_name" field.
func ProjectNameHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldProjectName, v))
}

// ProjectNameHasSuffix applies the HasSuffix predicate on the "project_name" field.
func ProjectNameHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldProjectName, v))
}

// ProjectNameIsNil applies the IsNil predicate on the "project_name" field.
func ProjectNameIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldProjectName))
}

// ProjectNameNotNil applies the NotNil predicate on the "project_name" field.
func ProjectNameNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldProjectName))
}

// ProjectNameEqualFold applies the EqualFold predicate on the "project_name" field.
func ProjectNameEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldProjectName, v))
}

// ProjectNameContainsFold applies the ContainsFold predicate on the "project_name" field.
func ProjectNameContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldProjectName, v))
}

// TotalActionsEQ applies the EQ predicate on the "total_actions" field.
func TotalActionsEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTotalActions, v))
}

// TotalActionsNEQ applies the NEQ predicate on the "total_actions" field.
func TotalActionsNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldTotalActions, v))
}

// TotalActionsIn applies the In predicate on the "total_actions" field.
func TotalActionsIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldTotalActions, vs...))
}

// TotalActionsNotIn applies the NotIn predicate on the "total_actions" field.
func TotalActionsNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldTotalActions, vs...))
}

// TotalActionsGT applies the GT predicate on the "total_actions" field.
func TotalActionsGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldTotalActions, v))
}

// TotalActionsGTE applies the GTE predicate on the "total_actions" field.
func TotalActionsGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldTotalActions, v))
}

// TotalActionsLT applies the LT predicate on the "total_actions" field.
func TotalActionsLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldTotalActions, v))
}

// TotalActionsLTE applies the LTE predicate on the "total_actions" field.
func TotalActionsLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldTotalActions, v))
}

// FilesReadEQ applies the EQ predicate on the "files_read" field.
func FilesReadEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFilesRead, v))
}

// FilesReadNEQ applies the NEQ predicate on the "files_read" field.
func FilesReadNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldFilesRead, v))
}

// FilesReadIn applies the In predicate on the "files_read" field.
func FilesReadIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldFilesRead, vs...))
}

// FilesReadNotIn applies the NotIn predicate on the "files_read" field.
func FilesReadNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldFilesRead, vs...))
}

// FilesReadGT applies the GT predicate on the "files_read" field.
func FilesReadGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldFilesRead, v))
}

// FilesReadGTE applies the GTE predicate on the "files_read" field.
func FilesReadGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldFilesRead, v))
}

// FilesReadLT applies the LT predicate on the "files_read" field.
func FilesReadLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldFilesRead, v))
}

// FilesReadLTE applies the LTE predicate on the "files_read" field.
func FilesReadLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldFilesRead, v))
}

// FilesWrittenEQ applies the EQ predicate on the "files_written" field.
func FilesWrittenEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFilesWritten, v))
}

// FilesWrittenNEQ applies the NEQ predicate on the "files_written" field.
func FilesWrittenNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldFilesWritten, v))
}

// FilesWrittenIn applies the In predicate on the "files_written" field.
func FilesWrittenIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldFilesWritten, vs...))
}

// FilesWrittenNotIn applies the NotIn predicate on the "files_written" field.
func FilesWrittenNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldFilesWritten, vs...))
}

// FilesWrittenGT applies the GT predicate on the "files_written" field.
func FilesWrittenGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldFilesWritten, v))
}

// FilesWrittenGTE applies the GTE predicate on the "files_written" field.
func FilesWrittenGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldFilesWritten, v))
}

// FilesWrittenLT applies the LT predicate on the "files_written" field.
func FilesWrittenLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldFilesWritten, v))
}

// FilesWrittenLTE applies the LTE predicate on the "files_written" field.
func FilesWrittenLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldFilesWritten, v))
}

// CommandsExecutedEQ applies the EQ predicate on the "commands_executed" field.
func CommandsExecutedEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCommandsExecuted, v))
}

// CommandsExecutedNEQ applies the NEQ predicate on the "commands_executed" field.
func CommandsExecutedNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCommandsExecuted, v))
}

// CommandsExecutedIn applies the In predicate on the "commands_executed" field.
func CommandsExecutedIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCommandsExecuted, vs...))
}

// CommandsExecutedNotIn applies the NotIn predicate on the "commands_executed" field.
func CommandsExecutedNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCommandsExecuted, vs...))
}

// CommandsExecutedGT applies the GT predicate on the "commands_executed" field.
func CommandsExecutedGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCommandsExecuted, v))
}

// CommandsExecutedGTE applies the GTE predicate on the "commands_executed" field.
func CommandsExecutedGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCommandsExecuted, v))
}

// CommandsExecutedLT applies the LT predicate on the "commands_executed" field.
func CommandsExecutedLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCommandsExecuted, v))
}

// CommandsExecutedLTE applies the LTE predicate on the "commands_executed" field.
func CommandsExecutedLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCommandsExecuted, v))
}

// ErrorsEQ applies the EQ predicate on the "errors" field.
func ErrorsEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldErrors, v))
}

// ErrorsNEQ applies the NEQ predicate on the "errors" field.
func ErrorsNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldErrors, v))
}

// ErrorsIn applies the In predicate on the "errors" field.
func ErrorsIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldErrors, vs...))
}

// ErrorsNotIn applies the NotIn predicate on the "errors" field.
func ErrorsNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldErrors, vs...))
}

// ErrorsGT applies the GT predicate on the "errors" field.
func ErrorsGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldErrors, v))
}

// ErrorsGTE applies the GTE predicate on the "errors" field.
func ErrorsGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldErrors, v))
}

// ErrorsLT applies the LT predicate on the "errors" field.
func ErrorsLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldErrors, v))
}

// ErrorsLTE applies the LTE predicate on the "errors" field.
func ErrorsLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldErrors, v))
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.AuditEvent) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
