"""Realistic event templates for normal (non-threat) activity."""

COMMAND_EXEC_TEMPLATES = [
    {"command": "npm run build", "description": "Build the project", "exit_code": 0},
    {"command": "npm test", "description": "Run test suite", "exit_code": 0},
    {"command": "npm run lint", "description": "Run linter", "exit_code": 0},
    {"command": "npm run dev", "description": "Start dev server", "exit_code": 0},
    {"command": "python -m pytest tests/", "description": "Run Python tests", "exit_code": 0},
    {"command": "python -m pytest tests/ -v --tb=short", "description": "Run Python tests verbose", "exit_code": 0},
    {"command": "go test ./...", "description": "Run Go tests", "exit_code": 0},
    {"command": "go build ./cmd/server", "description": "Build Go server", "exit_code": 0},
    {"command": "cargo test", "description": "Run Rust tests", "exit_code": 0},
    {"command": "cargo build --release", "description": "Build Rust release", "exit_code": 0},
    {"command": "make test", "description": "Run make test target", "exit_code": 0},
    {"command": "make build", "description": "Run make build target", "exit_code": 0},
    {"command": "gradle test", "description": "Run Gradle tests", "exit_code": 0},
    {"command": "mvn compile", "description": "Compile with Maven", "exit_code": 0},

    {"command": "git status", "description": "Show working tree status", "exit_code": 0},
    {"command": "git diff", "description": "Show unstaged changes", "exit_code": 0},
    {"command": "git diff --staged", "description": "Show staged changes", "exit_code": 0},
    {"command": "git log --oneline -10", "description": "Show recent commits", "exit_code": 0},
    {"command": "git log --oneline -5", "description": "Show last 5 commits", "exit_code": 0},
    {"command": "git add -A", "description": "Stage all changes", "exit_code": 0},
    {"command": "git checkout -b feature/new-api", "description": "Create feature branch", "exit_code": 0},
    {"command": "git checkout -b fix/auth-bug", "description": "Create bugfix branch", "exit_code": 0},
    {"command": "git push origin HEAD", "description": "Push current branch", "exit_code": 0},
    {"command": "git stash", "description": "Stash working changes", "exit_code": 0},
    {"command": "git pull origin main", "description": "Pull latest from main", "exit_code": 0},

    {"command": "npm install", "description": "Install dependencies", "exit_code": 0},
    {"command": "npm install express", "description": "Install express", "exit_code": 0},
    {"command": "npm install @types/node --save-dev", "description": "Install type definitions", "exit_code": 0},
    {"command": "pip install flask", "description": "Install flask", "exit_code": 0},
    {"command": "pip install -r requirements.txt", "description": "Install Python dependencies", "exit_code": 0},
    {"command": "yarn install", "description": "Install Yarn dependencies", "exit_code": 0},
    {"command": "go mod tidy", "description": "Tidy Go modules", "exit_code": 0},

    {"command": "ls -la src/", "description": "List source directory", "exit_code": 0},
    {"command": "ls -la", "description": "List current directory", "exit_code": 0},
    {"command": "cat package.json", "description": "Read package.json", "exit_code": 0},
    {"command": "wc -l src/**/*.ts", "description": "Count lines of TypeScript", "exit_code": 0},
    {"command": "grep -r 'TODO' src/", "description": "Find TODO comments", "exit_code": 0},
    {"command": "curl -s http://localhost:3000/health", "description": "Check local health endpoint", "exit_code": 0},
    {"command": "curl -s http://localhost:8080/api/status", "description": "Check API status", "exit_code": 0},
    {"command": "docker compose ps", "description": "List Docker containers", "exit_code": 0},
    {"command": "docker compose logs --tail 50 api", "description": "Tail API container logs", "exit_code": 0},
    {"command": "env | grep -i database", "description": "Check database env vars", "exit_code": 0},
    {"command": "psql -h localhost -U app -d mydb -c '\\dt'", "description": "List database tables", "exit_code": 0},
    {"command": "redis-cli ping", "description": "Check Redis connectivity", "exit_code": 0},

    {"command": "npm run build", "description": "Build the project", "exit_code": 1},
    {"command": "npm test", "description": "Run test suite", "exit_code": 1},
    {"command": "python -m pytest tests/", "description": "Run Python tests", "exit_code": 1},
    {"command": "cargo test", "description": "Run Rust tests", "exit_code": 1},
    {"command": "docker compose up -d", "description": "Start Docker services", "exit_code": 1},
    {"command": "go build ./cmd/server", "description": "Build Go server", "exit_code": 2},
    {"command": "make deploy", "description": "Deploy service", "exit_code": 1},
]

FILE_READ_TEMPLATES = [
    {"path": "/Users/{user}/project/src/index.ts"},
    {"path": "/Users/{user}/project/src/main.ts"},
    {"path": "/Users/{user}/project/src/app.ts"},
    {"path": "/Users/{user}/project/src/api/routes.ts"},
    {"path": "/Users/{user}/project/src/api/middleware.ts"},
    {"path": "/Users/{user}/project/src/api/auth.ts"},
    {"path": "/Users/{user}/project/src/components/App.tsx"},
    {"path": "/Users/{user}/project/src/components/Dashboard.tsx"},
    {"path": "/Users/{user}/project/src/components/Header.tsx"},
    {"path": "/Users/{user}/project/README.md"},
    {"path": "/Users/{user}/project/package.json"},
    {"path": "/Users/{user}/project/tsconfig.json"},
    {"path": "/Users/{user}/project/.github/workflows/ci.yml"},
    {"path": "/Users/{user}/project/Dockerfile"},
    {"path": "/Users/{user}/project/docker-compose.yml"},
    {"path": "/Users/{user}/project/src/utils/helpers.ts"},
    {"path": "/Users/{user}/project/src/utils/validation.ts"},
    {"path": "/Users/{user}/project/tests/api.test.ts"},
    {"path": "/Users/{user}/project/tests/auth.test.ts"},
    {"path": "/Users/{user}/project/src/models/user.py"},
    {"path": "/Users/{user}/project/src/models/order.py"},
    {"path": "/Users/{user}/project/src/config/database.ts"},
    {"path": "/Users/{user}/project/src/config/logger.ts"},
    {"path": "/Users/{user}/project/src/services/payment.ts"},
    {"path": "/Users/{user}/project/src/services/notification.ts"},
    {"path": "/Users/{user}/project/migrations/001_init.sql"},
    {"path": "/Users/{user}/project/go.mod"},
    {"path": "/Users/{user}/project/Cargo.toml"},
    {"path": "/Users/{user}/project/pyproject.toml"},
]

FILE_WRITE_TEMPLATES = [
    {"path": "/Users/{user}/project/src/index.ts",            "lines_added": 12, "lines_removed": 3},
    {"path": "/Users/{user}/project/src/api/routes.ts",       "lines_added": 25, "lines_removed": 8},
    {"path": "/Users/{user}/project/src/api/handlers.ts",     "lines_added": 40, "lines_removed": 0},
    {"path": "/Users/{user}/project/src/components/Modal.tsx", "lines_added": 45, "lines_removed": 0},
    {"path": "/Users/{user}/project/src/components/Form.tsx",  "lines_added": 60, "lines_removed": 5},
    {"path": "/Users/{user}/project/tests/modal.test.tsx",    "lines_added": 30, "lines_removed": 0},
    {"path": "/Users/{user}/project/tests/form.test.tsx",     "lines_added": 25, "lines_removed": 0},
    {"path": "/Users/{user}/project/src/utils/validators.ts", "lines_added": 18, "lines_removed": 5},
    {"path": "/Users/{user}/project/src/utils/format.ts",     "lines_added": 10, "lines_removed": 2},
    {"path": "/Users/{user}/project/src/styles/global.css",   "lines_added": 8,  "lines_removed": 2},
    {"path": "/Users/{user}/project/README.md",               "lines_added": 5,  "lines_removed": 1},
    {"path": "/Users/{user}/project/src/services/auth.ts",    "lines_added": 35, "lines_removed": 12},
    {"path": "/Users/{user}/project/src/middleware/cors.ts",   "lines_added": 15, "lines_removed": 0},
    {"path": "/Users/{user}/project/Dockerfile",              "lines_added": 3,  "lines_removed": 1},
    {"path": "/Users/{user}/project/src/models/schema.prisma", "lines_added": 20, "lines_removed": 5},
]

TOOL_USE_TEMPLATES = [
    {"tool": "Task",       "command": "Research authentication patterns for OAuth2", "description": "Spawned research agent"},
    {"tool": "Task",       "command": "Explore the codebase for payment integration", "description": "Spawned exploration agent"},
    {"tool": "Task",       "command": "Review the PR diff for security issues", "description": "Spawned code review agent"},
    {"tool": "WebSearch",  "command": "OpenSearch bulk API documentation", "description": "Web search"},
    {"tool": "WebSearch",  "command": "React useEffect cleanup pattern", "description": "Web search"},
    {"tool": "WebSearch",  "command": "Python asyncio best practices 2026", "description": "Web search"},
    {"tool": "WebFetch",   "command": "https://docs.example.com/api-reference/", "description": "Fetch documentation page"},
    {"tool": "WebFetch",   "command": "https://registry.npmjs.org/express/latest", "description": "Fetch npm package info"},
    {"tool": "Glob",       "command": "**/*.test.ts",  "description": "Find test files"},
    {"tool": "Glob",       "command": "**/*.tsx",      "description": "Find React components"},
    {"tool": "Glob",       "command": "src/**/*.py",   "description": "Find Python source files"},
    {"tool": "Grep",       "command": "handleSubmit",  "description": "Search for function usage"},
    {"tool": "Grep",       "command": "TODO|FIXME|HACK", "description": "Search for code annotations"},
    {"tool": "Grep",       "command": "import.*from", "description": "Search for imports"},
]

NOTIFICATION_TEMPLATES = [
    {"tool": "AskUserQuestion", "command": "Should I proceed with the refactoring?", "description": "User confirmation"},
    {"tool": "AskUserQuestion", "command": "Which database driver should I use: pg or mysql2?", "description": "User choice"},
    {"tool": "AskUserQuestion", "command": "The tests are failing. Should I fix the snapshot?", "description": "User confirmation"},
    {"tool": "AskUserQuestion", "command": "This will modify 12 files. Continue?", "description": "User confirmation"},
    {"tool": "AskUserQuestion", "command": "I found 3 approaches for this. Which do you prefer?", "description": "User choice"},
]

WORKING_DIRECTORIES = [
    "/Users/{user}/work/api-service",
    "/Users/{user}/work/web-app",
    "/Users/{user}/work/shared-lib",
    "/Users/{user}/work/infra",
    "/Users/{user}/work/mobile-app",
    "/Users/{user}/work/data-pipeline",
    "/Users/{user}/work/auth-service",
    "/Users/{user}/work/notification-service",
]
