// Code generated by ent, DO NOT EDIT.

package selfaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLTE(FieldID, id))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldTimestamp, v))
}

// AgentName applies equality check predicate on the "agent_name" field. It's identical to AgentNameEQ.
func AgentName(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldAgentName, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldErrorMessage, v))
}

// ToolVersion applies equality check predicate on the "tool_version" field. It's identical to ToolVersionEQ.
func ToolVersion(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldToolVersion, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLTE(FieldTimestamp, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v Action) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v Action) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...Action) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...Action) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotIn(FieldAction, vs...))
}

// AgentNameEQ applies the EQ predicate on the "agent_name" field.
func AgentNameEQ(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldAgentName, v))
}

// AgentNameNEQ applies the NEQ predicate on the "agent_name" field.
func AgentNameNEQ(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNEQ(FieldAgentName, v))
}

// AgentNameIn applies the In predicate on the "agent_name" field.
func AgentNameIn(vs ...string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIn(FieldAgentName, vs...))
}

// AgentNameNotIn applies the NotIn predicate on the "agent_name" field.
func AgentNameNotIn(vs ...string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotIn(FieldAgentName, vs...))
}

// AgentNameGT applies the GT predicate on the "agent_name" field.
func AgentNameGT(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGT(FieldAgentName, v))
}

// AgentNameGTE applies the GTE predicate on the "agent_name" field.
func AgentNameGTE(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGTE(FieldAgentName, v))
}

// AgentNameLT applies the LT predicate on the "agent_name" field.
func AgentNameLT(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLT(FieldAgentName, v))
}

// AgentNameLTE applies the LTE predicate on the "agent_name" field.
func AgentNameLTE(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLTE(FieldAgentName, v))
}

// AgentNameContains applies the Contains predicate on the "agent_name" field.
func AgentNameContains(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldContains(FieldAgentName, v))
}

// AgentNameHasPrefix applies the HasPrefix predicate on the "agent_name" field.
func AgentNameHasPrefix(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldHasPrefix(FieldAgentName, v))
}

// AgentNameHasSuffix applies the HasSuffix predicate on the "agent_name" field.
func AgentNameHasSuffix(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldHasSuffix(FieldAgentName, v))
}

// AgentNameIsNil applies the IsNil predicate on the "agent_name" field.
func AgentNameIsNil() predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIsNull(FieldAgentName))
}

// AgentNameNotNil applies the NotNil predicate on the "agent_name" field.
func AgentNameNotNil() predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotNull(FieldAgentName))
}

// AgentNameEqualFold applies the EqualFold predicate on the "agent_name" field.
func AgentNameEqualFold(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEqualFold(FieldAgentName, v))
}

// AgentNameContainsFold applies the ContainsFold predicate on the "agent_name" field.
func AgentNameContainsFold(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldContainsFold(FieldAgentName, v))
}

// DetailsIsNil applies the IsNil predicate on the "details" field.
func DetailsIsNil() predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIsNull(FieldDetails))
}

// DetailsNotNil applies the NotNil predicate on the "details" field.
func DetailsNotNil() predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotNull(FieldDetails))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v Result) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldResult, v))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v Result) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNEQ(FieldResult, v))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...Result) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIn(FieldResult, vs...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...Result) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotIn(FieldResult, vs...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ToolVersionEQ applies the EQ predicate on the "tool_version" field.
func ToolVersionEQ(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEQ(FieldToolVersion, v))
}

// ToolVersionNEQ applies the NEQ predicate on the "tool_version" field.
func ToolVersionNEQ(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNEQ(FieldToolVersion, v))
}

// ToolVersionIn applies the In predicate on the "tool_version" field.
func ToolVersionIn(vs ...string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldIn(FieldToolVersion, vs...))
}

// ToolVersionNotIn applies the NotIn predicate on the "tool_version" field.
func ToolVersionNotIn(vs ...string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldNotIn(FieldToolVersion, vs...))
}

// ToolVersionGT applies the GT predicate on the "tool_version" field.
func ToolVersionGT(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGT(FieldToolVersion, v))
}

// ToolVersionGTE applies the GTE predicate on the "tool_version" field.
func ToolVersionGTE(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldGTE(FieldToolVersion, v))
}

// ToolVersionLT applies the LT predicate on the "tool_version" field.
func ToolVersionLT(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLT(FieldToolVersion, v))
}

// ToolVersionLTE applies the LTE predicate on the "tool_version" field.
func ToolVersionLTE(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldLTE(FieldToolVersion, v))
}

// ToolVersionContains applies the Contains predicate on the "tool_version" field.
func ToolVersionContains(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldContains(FieldToolVersion, v))
}

// ToolVersionHasPrefix applies the HasPrefix predicate on the "tool_version" field.
func ToolVersionHasPrefix(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldHasPrefix(FieldToolVersion, v))
}

// ToolVersionHasSuffix applies the HasSuffix predicate on the "tool_version" field.
func ToolVersionHasSuffix(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldHasSuffix(FieldToolVersion, v))
}

// ToolVersionEqualFold applies the EqualFold predicate on the "tool_version" field.
func ToolVersionEqualFold(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldEqualFold(FieldToolVersion, v))
}

// ToolVersionContainsFold applies the ContainsFold predicate on the "tool_version" field.
func ToolVersionContainsFold(v string) predicate.SelfAudit {
	return predicate.SelfAudit(sql.FieldContainsFold(FieldToolVersion, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SelfAudit) predicate.SelfAudit {
	return predicate.SelfAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SelfAudit) predicate.SelfAudit {
	return predicate.SelfAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SelfAudit) predicate.SelfAudit {
	return predicate.SelfAudit(sql.NotPredicates(p))
}
