#!/bin/bash
set -euo pipefail

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists at ${ENV_FILE}"
  echo "To regenerate, delete it first: rm .env"
  exit 0
fi

# Generate a random password meeting OpenSearch requirements:
# min 8 chars, uppercase, lowercase, digit, special char
generate_password() {
  local upper lower digits rest
  upper=$(LC_ALL=C tr -dc 'A-Z' </dev/urandom | head -c 2)
  lower=$(LC_ALL=C tr -dc 'a-z' </dev/urandom | head -c 2)
  digits=$(LC_ALL=C tr -dc '0-9' </dev/urandom | head -c 2)
  rest=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 6)
  echo "${upper}${lower}${digits}${rest}@#" | fold -w1 | shuf | tr -d '\n'
}

OPENSEARCH_PASSWORD=$(generate_password)

cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh — do not commit this file

# OpenSearch
OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
OPENSEARCH_PORT=9200
OPENSEARCH_PERF_PORT=9600

# OpenSearch Dashboards
DASHBOARDS_PORT=5601

# Generator / collector
OPENSEARCH_URL=http://localhost:9200
GRYPH_INDEX_PREFIX=gryph-events
EOF

echo "Created ${ENV_FILE}"
echo "  OpenSearch admin password: ${OPENSEARCH_PASSWORD}"
