// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AarmDeferredAction is the predicate function for aarmdeferredaction builders.
type AarmDeferredAction func(*sql.Selector)

// AarmReceipt is the predicate function for aarmreceipt builders.
type AarmReceipt func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// AuditStreamCursor is the predicate function for auditstreamcursor builders.
type AuditStreamCursor func(*sql.Selector)

// ContextEntry is the predicate function for contextentry builders.
type ContextEntry func(*sql.Selector)

// ContextState is the predicate function for contextstate builders.
type ContextState func(*sql.Selector)

// EventStreamCursor is the predicate function for eventstreamcursor builders.
type EventStreamCursor func(*sql.Selector)

// SelfAudit is the predicate function for selfaudit builders.
type SelfAudit func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)
