// Code generated by ent, DO NOT EDIT.

package aarmcontextaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldSessionID, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldEventID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldTimestamp, v))
}

// Tool applies equality check predicate on the "tool" field. It's identical to ToolEQ.
func Tool(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldTool, v))
}

// Agent applies equality check predicate on the "agent" field. It's identical to AgentEQ.
func Agent(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldAgent, v))
}

// Project applies equality check predicate on the "project" field. It's identical to ProjectEQ.
func Project(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldProject, v))
}

// WorkingDir applies equality check predicate on the "working_dir" field. It's identical to WorkingDirEQ.
func WorkingDir(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldWorkingDir, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldErrorMessage, v))
}

// InjectionScore applies equality check predicate on the "injection_score" field. It's identical to InjectionScoreEQ.
func InjectionScore(v float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldInjectionScore, v))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldSequence, v))
}

// PrevHash applies equality check predicate on the "prev_hash" field. It's identical to PrevHashEQ.
func PrevHash(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldPrevHash, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldHash, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldSessionID, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v uuid.UUID) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldEventID, v))
}

// EventIDIsNil applies the IsNil predicate on the "event_id" field.
func EventIDIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldEventID))
}

// EventIDNotNil applies the NotNil predicate on the "event_id" field.
func EventIDNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldEventID))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldTimestamp, v))
}

// ActionTypeEQ applies the EQ predicate on the "action_type" field.
func ActionTypeEQ(v ActionType) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldActionType, v))
}

// ActionTypeNEQ applies the NEQ predicate on the "action_type" field.
func ActionTypeNEQ(v ActionType) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldActionType, v))
}

// ActionTypeIn applies the In predicate on the "action_type" field.
func ActionTypeIn(vs ...ActionType) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldActionType, vs...))
}

// ActionTypeNotIn applies the NotIn predicate on the "action_type" field.
func ActionTypeNotIn(vs ...ActionType) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldActionType, vs...))
}

// ToolEQ applies the EQ predicate on the "tool" field.
func ToolEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldTool, v))
}

// ToolNEQ applies the NEQ predicate on the "tool" field.
func ToolNEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldTool, v))
}

// ToolIn applies the In predicate on the "tool" field.
func ToolIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldTool, vs...))
}

// ToolNotIn applies the NotIn predicate on the "tool" field.
func ToolNotIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldTool, vs...))
}

// ToolGT applies the GT predicate on the "tool" field.
func ToolGT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldTool, v))
}

// ToolGTE applies the GTE predicate on the "tool" field.
func ToolGTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldTool, v))
}

// ToolLT applies the LT predicate on the "tool" field.
func ToolLT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldTool, v))
}

// ToolLTE applies the LTE predicate on the "tool" field.
func ToolLTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldTool, v))
}

// ToolContains applies the Contains predicate on the "tool" field.
func ToolContains(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContains(FieldTool, v))
}

// ToolHasPrefix applies the HasPrefix predicate on the "tool" field.
func ToolHasPrefix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasPrefix(FieldTool, v))
}

// ToolHasSuffix applies the HasSuffix predicate on the "tool" field.
func ToolHasSuffix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasSuffix(FieldTool, v))
}

// ToolIsNil applies the IsNil predicate on the "tool" field.
func ToolIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldTool))
}

// ToolNotNil applies the NotNil predicate on the "tool" field.
func ToolNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldTool))
}

// ToolEqualFold applies the EqualFold predicate on the "tool" field.
func ToolEqualFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEqualFold(FieldTool, v))
}

// ToolContainsFold applies the ContainsFold predicate on the "tool" field.
func ToolContainsFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContainsFold(FieldTool, v))
}

// AgentEQ applies the EQ predicate on the "agent" field.
func AgentEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldAgent, v))
}

// AgentNEQ applies the NEQ predicate on the "agent" field.
func AgentNEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldAgent, v))
}

// AgentIn applies the In predicate on the "agent" field.
func AgentIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldAgent, vs...))
}

// AgentNotIn applies the NotIn predicate on the "agent" field.
func AgentNotIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldAgent, vs...))
}

// AgentGT applies the GT predicate on the "agent" field.
func AgentGT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldAgent, v))
}

// AgentGTE applies the GTE predicate on the "agent" field.
func AgentGTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldAgent, v))
}

// AgentLT applies the LT predicate on the "agent" field.
func AgentLT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldAgent, v))
}

// AgentLTE applies the LTE predicate on the "agent" field.
func AgentLTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldAgent, v))
}

// AgentContains applies the Contains predicate on the "agent" field.
func AgentContains(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContains(FieldAgent, v))
}

// AgentHasPrefix applies the HasPrefix predicate on the "agent" field.
func AgentHasPrefix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasPrefix(FieldAgent, v))
}

// AgentHasSuffix applies the HasSuffix predicate on the "agent" field.
func AgentHasSuffix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasSuffix(FieldAgent, v))
}

// AgentIsNil applies the IsNil predicate on the "agent" field.
func AgentIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldAgent))
}

// AgentNotNil applies the NotNil predicate on the "agent" field.
func AgentNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldAgent))
}

// AgentEqualFold applies the EqualFold predicate on the "agent" field.
func AgentEqualFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEqualFold(FieldAgent, v))
}

// AgentContainsFold applies the ContainsFold predicate on the "agent" field.
func AgentContainsFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContainsFold(FieldAgent, v))
}

// ProjectEQ applies the EQ predicate on the "project" field.
func ProjectEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldProject, v))
}

// ProjectNEQ applies the NEQ predicate on the "project" field.
func ProjectNEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldProject, v))
}

// ProjectIn applies the In predicate on the "project" field.
func ProjectIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldProject, vs...))
}

// ProjectNotIn applies the NotIn predicate on the "project" field.
func ProjectNotIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldProject, vs...))
}

// ProjectGT applies the GT predicate on the "project" field.
func ProjectGT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldProject, v))
}

// ProjectGTE applies the GTE predicate on the "project" field.
func ProjectGTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldProject, v))
}

// ProjectLT applies the LT predicate on the "project" field.
func ProjectLT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldProject, v))
}

// ProjectLTE applies the LTE predicate on the "project" field.
func ProjectLTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldProject, v))
}

// ProjectContains applies the Contains predicate on the "project" field.
func ProjectContains(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContains(FieldProject, v))
}

// ProjectHasPrefix applies the HasPrefix predicate on the "project" field.
func ProjectHasPrefix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasPrefix(FieldProject, v))
}

// ProjectHasSuffix applies the HasSuffix predicate on the "project" field.
func ProjectHasSuffix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasSuffix(FieldProject, v))
}

// ProjectIsNil applies the IsNil predicate on the "project" field.
func ProjectIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldProject))
}

// ProjectNotNil applies the NotNil predicate on the "project" field.
func ProjectNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldProject))
}

// ProjectEqualFold applies the EqualFold predicate on the "project" field.
func ProjectEqualFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEqualFold(FieldProject, v))
}

// ProjectContainsFold applies the ContainsFold predicate on the "project" field.
func ProjectContainsFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContainsFold(FieldProject, v))
}

// WorkingDirEQ applies the EQ predicate on the "working_dir" field.
func WorkingDirEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldWorkingDir, v))
}

// WorkingDirNEQ applies the NEQ predicate on the "working_dir" field.
func WorkingDirNEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldWorkingDir, v))
}

// WorkingDirIn applies the In predicate on the "working_dir" field.
func WorkingDirIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldWorkingDir, vs...))
}

// WorkingDirNotIn applies the NotIn predicate on the "working_dir" field.
func WorkingDirNotIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldWorkingDir, vs...))
}

// WorkingDirGT applies the GT predicate on the "working_dir" field.
func WorkingDirGT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldWorkingDir, v))
}

// WorkingDirGTE applies the GTE predicate on the "working_dir" field.
func WorkingDirGTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldWorkingDir, v))
}

// WorkingDirLT applies the LT predicate on the "working_dir" field.
func WorkingDirLT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldWorkingDir, v))
}

// WorkingDirLTE applies the LTE predicate on the "working_dir" field.
func WorkingDirLTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldWorkingDir, v))
}

// WorkingDirContains applies the Contains predicate on the "working_dir" field.
func WorkingDirContains(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContains(FieldWorkingDir, v))
}

// WorkingDirHasPrefix applies the HasPrefix predicate on the "working_dir" field.
func WorkingDirHasPrefix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasPrefix(FieldWorkingDir, v))
}

// WorkingDirHasSuffix applies the HasSuffix predicate on the "working_dir" field.
func WorkingDirHasSuffix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasSuffix(FieldWorkingDir, v))
}

// WorkingDirIsNil applies the IsNil predicate on the "working_dir" field.
func WorkingDirIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldWorkingDir))
}

// WorkingDirNotNil applies the NotNil predicate on the "working_dir" field.
func WorkingDirNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldWorkingDir))
}

// WorkingDirEqualFold applies the EqualFold predicate on the "working_dir" field.
func WorkingDirEqualFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEqualFold(FieldWorkingDir, v))
}

// WorkingDirContainsFold applies the ContainsFold predicate on the "working_dir" field.
func WorkingDirContainsFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContainsFold(FieldWorkingDir, v))
}

// ResultStatusEQ applies the EQ predicate on the "result_status" field.
func ResultStatusEQ(v ResultStatus) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldResultStatus, v))
}

// ResultStatusNEQ applies the NEQ predicate on the "result_status" field.
func ResultStatusNEQ(v ResultStatus) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldResultStatus, v))
}

// ResultStatusIn applies the In predicate on the "result_status" field.
func ResultStatusIn(vs ...ResultStatus) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldResultStatus, vs...))
}

// ResultStatusNotIn applies the NotIn predicate on the "result_status" field.
func ResultStatusNotIn(vs ...ResultStatus) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldResultStatus, vs...))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldDurationMs))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldContainsFold(FieldErrorMessage, v))
}

// DataClassificationsIsNil applies the IsNil predicate on the "data_classifications" field.
func DataClassificationsIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldDataClassifications))
}

// DataClassificationsNotNil applies the NotNil predicate on the "data_classifications" field.
func DataClassificationsNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldDataClassifications))
}

// InjectionScoreEQ applies the EQ predicate on the "injection_score" field.
func InjectionScoreEQ(v float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldInjectionScore, v))
}

// InjectionScoreNEQ applies the NEQ predicate on the "injection_score" field.
func InjectionScoreNEQ(v float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldInjectionScore, v))
}

// InjectionScoreIn applies the In predicate on the "injection_score" field.
func InjectionScoreIn(vs ...float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldInjectionScore, vs...))
}

// InjectionScoreNotIn applies the NotIn predicate on the "injection_score" field.
func InjectionScoreNotIn(vs ...float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldInjectionScore, vs...))
}

// InjectionScoreGT applies the GT predicate on the "injection_score" field.
func InjectionScoreGT(v float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldInjectionScore, v))
}

// InjectionScoreGTE applies the GTE predicate on the "injection_score" field.
func InjectionScoreGTE(v float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldInjectionScore, v))
}

// InjectionScoreLT applies the LT predicate on the "injection_score" field.
func InjectionScoreLT(v float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldInjectionScore, v))
}

// InjectionScoreLTE applies the LTE predicate on the "injection_score" field.
func InjectionScoreLTE(v float32) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldInjectionScore, v))
}

// InjectionScoreIsNil applies the IsNil predicate on the "injection_score" field.
func InjectionScoreIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldInjectionScore))
}

// InjectionScoreNotNil applies the NotNil predicate on the "injection_score" field.
func InjectionScoreNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldInjectionScore))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int64) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldSequence, v))
}

// SequenceIsNil applies the IsNil predicate on the "sequence" field.
func SequenceIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldSequence))
}

// SequenceNotNil applies the NotNil predicate on the "sequence" field.
func SequenceNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldSequence))
}

// PrevHashEQ applies the EQ predicate on the "prev_hash" field.
func PrevHashEQ(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldPrevHash, v))
}

// PrevHashNEQ applies the NEQ predicate on the "prev_hash" field.
func PrevHashNEQ(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldPrevHash, v))
}

// PrevHashIn applies the In predicate on the "prev_hash" field.
func PrevHashIn(vs ...[]byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldPrevHash, vs...))
}

// PrevHashNotIn applies the NotIn predicate on the "prev_hash" field.
func PrevHashNotIn(vs ...[]byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldPrevHash, vs...))
}

// PrevHashGT applies the GT predicate on the "prev_hash" field.
func PrevHashGT(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldPrevHash, v))
}

// PrevHashGTE applies the GTE predicate on the "prev_hash" field.
func PrevHashGTE(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldPrevHash, v))
}

// PrevHashLT applies the LT predicate on the "prev_hash" field.
func PrevHashLT(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldPrevHash, v))
}

// PrevHashLTE applies the LTE predicate on the "prev_hash" field.
func PrevHashLTE(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldPrevHash, v))
}

// PrevHashIsNil applies the IsNil predicate on the "prev_hash" field.
func PrevHashIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldPrevHash))
}

// PrevHashNotNil applies the NotNil predicate on the "prev_hash" field.
func PrevHashNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldPrevHash))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...[]byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...[]byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v []byte) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldLTE(FieldHash, v))
}

// HashIsNil applies the IsNil predicate on the "hash" field.
func HashIsNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldIsNull(FieldHash))
}

// HashNotNil applies the NotNil predicate on the "hash" field.
func HashNotNil() predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.FieldNotNull(FieldHash))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AarmContextAction) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AarmContextAction) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AarmContextAction) predicate.AarmContextAction {
	return predicate.AarmContextAction(sql.NotPredicates(p))
}
