// Code generated by ent, DO NOT EDIT.

package streamcheckpoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the streamcheckpoint type in the database.
	Label = "stream_checkpoint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldLastEventID holds the string denoting the last_event_id field in the database.
	FieldLastEventID = "last_event_id"
	// FieldLastSelfAuditID holds the string denoting the last_self_audit_id field in the database.
	FieldLastSelfAuditID = "last_self_audit_id"
	// Table holds the table name of the streamcheckpoint in the database.
	Table = "stream_checkpoints"
)

// Columns holds all SQL columns for streamcheckpoint fields.
var Columns = []string{
	FieldID,
	FieldLastSyncedAt,
	FieldLastEventID,
	FieldLastSelfAuditID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLastSyncedAt holds the default value on creation for the "last_synced_at" field.
	DefaultLastSyncedAt func() time.Time
)

// OrderOption defines the ordering options for the StreamCheckpoint queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByLastEventID orders the results by the last_event_id field.
func ByLastEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEventID, opts...).ToFunc()
}

// ByLastSelfAuditID orders the results by the last_self_audit_id field.
func ByLastSelfAuditID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSelfAuditID, opts...).ToFunc()
}
