// Package schema exposes Gryph's generated JSON schemas as embedded strings
// so they can be served by the CLI without reading the filesystem.
package schema

import _ "embed"

//go:embed policy.schema.json
var policyJSON string

// PolicyJSON returns the JSON Schema document for Gryph security policies.
// The source of truth is regenerated by `make generate-schema`; a drift test
// in aarm/pdp guards against the schema falling out of sync with the Go types.
func PolicyJSON() string {
	return policyJSON
}
