// Code generated by ent, DO NOT EDIT.

package aarmcontextstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aarmcontextstate type in the database.
	Label = "aarm_context_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldFirstSeenAt holds the string denoting the first_seen_at field in the database.
	FieldFirstSeenAt = "first_seen_at"
	// FieldLastActionAt holds the string denoting the last_action_at field in the database.
	FieldLastActionAt = "last_action_at"
	// FieldTotalActions holds the string denoting the total_actions field in the database.
	FieldTotalActions = "total_actions"
	// FieldFilesRead holds the string denoting the files_read field in the database.
	FieldFilesRead = "files_read"
	// FieldFilesWritten holds the string denoting the files_written field in the database.
	FieldFilesWritten = "files_written"
	// FieldCommandsExecuted holds the string denoting the commands_executed field in the database.
	FieldCommandsExecuted = "commands_executed"
	// FieldNetworkRequests holds the string denoting the network_requests field in the database.
	FieldNetworkRequests = "network_requests"
	// FieldErrors holds the string denoting the errors field in the database.
	FieldErrors = "errors"
	// FieldToolsUsed holds the string denoting the tools_used field in the database.
	FieldToolsUsed = "tools_used"
	// FieldClassificationsSeen holds the string denoting the classifications_seen field in the database.
	FieldClassificationsSeen = "classifications_seen"
	// FieldEntitiesSeen holds the string denoting the entities_seen field in the database.
	FieldEntitiesSeen = "entities_seen"
	// FieldSemanticDrift holds the string denoting the semantic_drift field in the database.
	FieldSemanticDrift = "semantic_drift"
	// Table holds the table name of the aarmcontextstate in the database.
	Table = "aarm_context_states"
)

// Columns holds all SQL columns for aarmcontextstate fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldFirstSeenAt,
	FieldLastActionAt,
	FieldTotalActions,
	FieldFilesRead,
	FieldFilesWritten,
	FieldCommandsExecuted,
	FieldNetworkRequests,
	FieldErrors,
	FieldToolsUsed,
	FieldClassificationsSeen,
	FieldEntitiesSeen,
	FieldSemanticDrift,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFirstSeenAt holds the default value on creation for the "first_seen_at" field.
	DefaultFirstSeenAt func() time.Time
	// DefaultLastActionAt holds the default value on creation for the "last_action_at" field.
	DefaultLastActionAt func() time.Time
	// DefaultTotalActions holds the default value on creation for the "total_actions" field.
	DefaultTotalActions int
	// DefaultFilesRead holds the default value on creation for the "files_read" field.
	DefaultFilesRead int
	// DefaultFilesWritten holds the default value on creation for the "files_written" field.
	DefaultFilesWritten int
	// DefaultCommandsExecuted holds the default value on creation for the "commands_executed" field.
	DefaultCommandsExecuted int
	// DefaultNetworkRequests holds the default value on creation for the "network_requests" field.
	DefaultNetworkRequests int
	// DefaultErrors holds the default value on creation for the "errors" field.
	DefaultErrors int
	// DefaultSemanticDrift holds the default value on creation for the "semantic_drift" field.
	DefaultSemanticDrift float64
)

// OrderOption defines the ordering options for the AarmContextState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByFirstSeenAt orders the results by the first_seen_at field.
func ByFirstSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeenAt, opts...).ToFunc()
}

// ByLastActionAt orders the results by the last_action_at field.
func ByLastActionAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActionAt, opts...).ToFunc()
}

// ByTotalActions orders the results by the total_actions field.
func ByTotalActions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalActions, opts...).ToFunc()
}

// ByFilesRead orders the results by the files_read field.
func ByFilesRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilesRead, opts...).ToFunc()
}

// ByFilesWritten orders the results by the files_written field.
func ByFilesWritten(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilesWritten, opts...).ToFunc()
}

// ByCommandsExecuted orders the results by the commands_executed field.
func ByCommandsExecuted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommandsExecuted, opts...).ToFunc()
}

// ByNetworkRequests orders the results by the network_requests field.
func ByNetworkRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetworkRequests, opts...).ToFunc()
}

// ByErrors orders the results by the errors field.
func ByErrors(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrors, opts...).ToFunc()
}

// BySemanticDrift orders the results by the semantic_drift field.
func BySemanticDrift(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSemanticDrift, opts...).ToFunc()
}
