// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/aarmreceipt"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// AarmReceiptUpdate is the builder for updating AarmReceipt entities.
type AarmReceiptUpdate struct {
	config
	hooks    []Hook
	mutation *AarmReceiptMutation
}

// Where appends a list predicates to the AarmReceiptUpdate builder.
func (_u *AarmReceiptUpdate) Where(ps ...predicate.AarmReceipt) *AarmReceiptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AarmReceiptUpdate) SetSessionID(v uuid.UUID) *AarmReceiptUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableSessionID(v *uuid.UUID) *AarmReceiptUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetActionID sets the "action_id" field.
func (_u *AarmReceiptUpdate) SetActionID(v uuid.UUID) *AarmReceiptUpdate {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableActionID(v *uuid.UUID) *AarmReceiptUpdate {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// ClearActionID clears the value of the "action_id" field.
func (_u *AarmReceiptUpdate) ClearActionID() *AarmReceiptUpdate {
	_u.mutation.ClearActionID()
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *AarmReceiptUpdate) SetEventID(v uuid.UUID) *AarmReceiptUpdate {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableEventID(v *uuid.UUID) *AarmReceiptUpdate {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// ClearEventID clears the value of the "event_id" field.
func (_u *AarmReceiptUpdate) ClearEventID() *AarmReceiptUpdate {
	_u.mutation.ClearEventID()
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *AarmReceiptUpdate) SetSequence(v int64) *AarmReceiptUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableSequence(v *int64) *AarmReceiptUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *AarmReceiptUpdate) AddSequence(v int64) *AarmReceiptUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetAgent sets the "agent" field.
func (_u *AarmReceiptUpdate) SetAgent(v string) *AarmReceiptUpdate {
	_u.mutation.SetAgent(v)
	return _u
}

// SetNillableAgent sets the "agent" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableAgent(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetAgent(*v)
	}
	return _u
}

// ClearAgent clears the value of the "agent" field.
func (_u *AarmReceiptUpdate) ClearAgent() *AarmReceiptUpdate {
	_u.mutation.ClearAgent()
	return _u
}

// SetTool sets the "tool" field.
func (_u *AarmReceiptUpdate) SetTool(v string) *AarmReceiptUpdate {
	_u.mutation.SetTool(v)
	return _u
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableTool(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetTool(*v)
	}
	return _u
}

// ClearTool clears the value of the "tool" field.
func (_u *AarmReceiptUpdate) ClearTool() *AarmReceiptUpdate {
	_u.mutation.ClearTool()
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *AarmReceiptUpdate) SetActionType(v string) *AarmReceiptUpdate {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableActionType(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *AarmReceiptUpdate) SetProject(v string) *AarmReceiptUpdate {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableProject(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// ClearProject clears the value of the "project" field.
func (_u *AarmReceiptUpdate) ClearProject() *AarmReceiptUpdate {
	_u.mutation.ClearProject()
	return _u
}

// SetDecision sets the "decision" field.
func (_u *AarmReceiptUpdate) SetDecision(v string) *AarmReceiptUpdate {
	_u.mutation.SetDecision(v)
	return _u
}

// SetNillableDecision sets the "decision" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableDecision(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetDecision(*v)
	}
	return _u
}

// SetMatchedRuleIds sets the "matched_rule_ids" field.
func (_u *AarmReceiptUpdate) SetMatchedRuleIds(v []string) *AarmReceiptUpdate {
	_u.mutation.SetMatchedRuleIds(v)
	return _u
}

// AppendMatchedRuleIds appends value to the "matched_rule_ids" field.
func (_u *AarmReceiptUpdate) AppendMatchedRuleIds(v []string) *AarmReceiptUpdate {
	_u.mutation.AppendMatchedRuleIds(v)
	return _u
}

// ClearMatchedRuleIds clears the value of the "matched_rule_ids" field.
func (_u *AarmReceiptUpdate) ClearMatchedRuleIds() *AarmReceiptUpdate {
	_u.mutation.ClearMatchedRuleIds()
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *AarmReceiptUpdate) SetSeverity(v string) *AarmReceiptUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableSeverity(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// ClearSeverity clears the value of the "severity" field.
func (_u *AarmReceiptUpdate) ClearSeverity() *AarmReceiptUpdate {
	_u.mutation.ClearSeverity()
	return _u
}

// SetMessage sets the "message" field.
func (_u *AarmReceiptUpdate) SetMessage(v string) *AarmReceiptUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableMessage(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *AarmReceiptUpdate) ClearMessage() *AarmReceiptUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetResultStatus sets the "result_status" field.
func (_u *AarmReceiptUpdate) SetResultStatus(v aarmreceipt.ResultStatus) *AarmReceiptUpdate {
	_u.mutation.SetResultStatus(v)
	return _u
}

// SetNillableResultStatus sets the "result_status" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableResultStatus(v *aarmreceipt.ResultStatus) *AarmReceiptUpdate {
	if v != nil {
		_u.SetResultStatus(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AarmReceiptUpdate) SetDurationMs(v int64) *AarmReceiptUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableDurationMs(v *int64) *AarmReceiptUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AarmReceiptUpdate) AddDurationMs(v int64) *AarmReceiptUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AarmReceiptUpdate) ClearDurationMs() *AarmReceiptUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AarmReceiptUpdate) SetErrorMessage(v string) *AarmReceiptUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableErrorMessage(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AarmReceiptUpdate) ClearErrorMessage() *AarmReceiptUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *AarmReceiptUpdate) SetSnapshot(v map[string]interface{}) *AarmReceiptUpdate {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *AarmReceiptUpdate) ClearSnapshot() *AarmReceiptUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetActionPayload sets the "action_payload" field.
func (_u *AarmReceiptUpdate) SetActionPayload(v map[string]interface{}) *AarmReceiptUpdate {
	_u.mutation.SetActionPayload(v)
	return _u
}

// ClearActionPayload clears the value of the "action_payload" field.
func (_u *AarmReceiptUpdate) ClearActionPayload() *AarmReceiptUpdate {
	_u.mutation.ClearActionPayload()
	return _u
}

// SetPrevHash sets the "prev_hash" field.
func (_u *AarmReceiptUpdate) SetPrevHash(v []byte) *AarmReceiptUpdate {
	_u.mutation.SetPrevHash(v)
	return _u
}

// ClearPrevHash clears the value of the "prev_hash" field.
func (_u *AarmReceiptUpdate) ClearPrevHash() *AarmReceiptUpdate {
	_u.mutation.ClearPrevHash()
	return _u
}

// SetHash sets the "hash" field.
func (_u *AarmReceiptUpdate) SetHash(v []byte) *AarmReceiptUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetSubagentID sets the "subagent_id" field.
func (_u *AarmReceiptUpdate) SetSubagentID(v string) *AarmReceiptUpdate {
	_u.mutation.SetSubagentID(v)
	return _u
}

// SetNillableSubagentID sets the "subagent_id" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableSubagentID(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetSubagentID(*v)
	}
	return _u
}

// ClearSubagentID clears the value of the "subagent_id" field.
func (_u *AarmReceiptUpdate) ClearSubagentID() *AarmReceiptUpdate {
	_u.mutation.ClearSubagentID()
	return _u
}

// SetSubagentType sets the "subagent_type" field.
func (_u *AarmReceiptUpdate) SetSubagentType(v string) *AarmReceiptUpdate {
	_u.mutation.SetSubagentType(v)
	return _u
}

// SetNillableSubagentType sets the "subagent_type" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableSubagentType(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetSubagentType(*v)
	}
	return _u
}

// ClearSubagentType clears the value of the "subagent_type" field.
func (_u *AarmReceiptUpdate) ClearSubagentType() *AarmReceiptUpdate {
	_u.mutation.ClearSubagentType()
	return _u
}

// SetPolicyHash sets the "policy_hash" field.
func (_u *AarmReceiptUpdate) SetPolicyHash(v []byte) *AarmReceiptUpdate {
	_u.mutation.SetPolicyHash(v)
	return _u
}

// ClearPolicyHash clears the value of the "policy_hash" field.
func (_u *AarmReceiptUpdate) ClearPolicyHash() *AarmReceiptUpdate {
	_u.mutation.ClearPolicyHash()
	return _u
}

// SetSignature sets the "signature" field.
func (_u *AarmReceiptUpdate) SetSignature(v []byte) *AarmReceiptUpdate {
	_u.mutation.SetSignature(v)
	return _u
}

// ClearSignature clears the value of the "signature" field.
func (_u *AarmReceiptUpdate) ClearSignature() *AarmReceiptUpdate {
	_u.mutation.ClearSignature()
	return _u
}

// SetSignerKeyID sets the "signer_key_id" field.
func (_u *AarmReceiptUpdate) SetSignerKeyID(v string) *AarmReceiptUpdate {
	_u.mutation.SetSignerKeyID(v)
	return _u
}

// SetNillableSignerKeyID sets the "signer_key_id" field if the given value is not nil.
func (_u *AarmReceiptUpdate) SetNillableSignerKeyID(v *string) *AarmReceiptUpdate {
	if v != nil {
		_u.SetSignerKeyID(*v)
	}
	return _u
}

// ClearSignerKeyID clears the value of the "signer_key_id" field.
func (_u *AarmReceiptUpdate) ClearSignerKeyID() *AarmReceiptUpdate {
	_u.mutation.ClearSignerKeyID()
	return _u
}

// Mutation returns the AarmReceiptMutation object of the builder.
func (_u *AarmReceiptUpdate) Mutation() *AarmReceiptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AarmReceiptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AarmReceiptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AarmReceiptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AarmReceiptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AarmReceiptUpdate) check() error {
	if v, ok := _u.mutation.Sequence(); ok {
		if err := aarmreceipt.SequenceValidator(v); err != nil {
			return &ValidationError{Name: "sequence", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.sequence": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultStatus(); ok {
		if err := aarmreceipt.ResultStatusValidator(v); err != nil {
			return &ValidationError{Name: "result_status", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.result_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrevHash(); ok {
		if err := aarmreceipt.PrevHashValidator(v); err != nil {
			return &ValidationError{Name: "prev_hash", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.prev_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := aarmreceipt.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PolicyHash(); ok {
		if err := aarmreceipt.PolicyHashValidator(v); err != nil {
			return &ValidationError{Name: "policy_hash", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.policy_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AarmReceiptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aarmreceipt.Table, aarmreceipt.Columns, sqlgraph.NewFieldSpec(aarmreceipt.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(aarmreceipt.FieldSessionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ActionID(); ok {
		_spec.SetField(aarmreceipt.FieldActionID, field.TypeUUID, value)
	}
	if _u.mutation.ActionIDCleared() {
		_spec.ClearField(aarmreceipt.FieldActionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(aarmreceipt.FieldEventID, field.TypeUUID, value)
	}
	if _u.mutation.EventIDCleared() {
		_spec.ClearField(aarmreceipt.FieldEventID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(aarmreceipt.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(aarmreceipt.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Agent(); ok {
		_spec.SetField(aarmreceipt.FieldAgent, field.TypeString, value)
	}
	if _u.mutation.AgentCleared() {
		_spec.ClearField(aarmreceipt.FieldAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Tool(); ok {
		_spec.SetField(aarmreceipt.FieldTool, field.TypeString, value)
	}
	if _u.mutation.ToolCleared() {
		_spec.ClearField(aarmreceipt.FieldTool, field.TypeString)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(aarmreceipt.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(aarmreceipt.FieldProject, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		_spec.ClearField(aarmreceipt.FieldProject, field.TypeString)
	}
	if value, ok := _u.mutation.Decision(); ok {
		_spec.SetField(aarmreceipt.FieldDecision, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedRuleIds(); ok {
		_spec.SetField(aarmreceipt.FieldMatchedRuleIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMatchedRuleIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, aarmreceipt.FieldMatchedRuleIds, value)
		})
	}
	if _u.mutation.MatchedRuleIdsCleared() {
		_spec.ClearField(aarmreceipt.FieldMatchedRuleIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(aarmreceipt.FieldSeverity, field.TypeString, value)
	}
	if _u.mutation.SeverityCleared() {
		_spec.ClearField(aarmreceipt.FieldSeverity, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(aarmreceipt.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(aarmreceipt.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ResultStatus(); ok {
		_spec.SetField(aarmreceipt.FieldResultStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(aarmreceipt.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(aarmreceipt.FieldDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(aarmreceipt.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(aarmreceipt.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(aarmreceipt.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(aarmreceipt.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(aarmreceipt.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActionPayload(); ok {
		_spec.SetField(aarmreceipt.FieldActionPayload, field.TypeJSON, value)
	}
	if _u.mutation.ActionPayloadCleared() {
		_spec.ClearField(aarmreceipt.FieldActionPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.PrevHash(); ok {
		_spec.SetField(aarmreceipt.FieldPrevHash, field.TypeBytes, value)
	}
	if _u.mutation.PrevHashCleared() {
		_spec.ClearField(aarmreceipt.FieldPrevHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(aarmreceipt.FieldHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.SubagentID(); ok {
		_spec.SetField(aarmreceipt.FieldSubagentID, field.TypeString, value)
	}
	if _u.mutation.SubagentIDCleared() {
		_spec.ClearField(aarmreceipt.FieldSubagentID, field.TypeString)
	}
	if value, ok := _u.mutation.SubagentType(); ok {
		_spec.SetField(aarmreceipt.FieldSubagentType, field.TypeString, value)
	}
	if _u.mutation.SubagentTypeCleared() {
		_spec.ClearField(aarmreceipt.FieldSubagentType, field.TypeString)
	}
	if value, ok := _u.mutation.PolicyHash(); ok {
		_spec.SetField(aarmreceipt.FieldPolicyHash, field.TypeBytes, value)
	}
	if _u.mutation.PolicyHashCleared() {
		_spec.ClearField(aarmreceipt.FieldPolicyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(aarmreceipt.FieldSignature, field.TypeBytes, value)
	}
	if _u.mutation.SignatureCleared() {
		_spec.ClearField(aarmreceipt.FieldSignature, field.TypeBytes)
	}
	if value, ok := _u.mutation.SignerKeyID(); ok {
		_spec.SetField(aarmreceipt.FieldSignerKeyID, field.TypeString, value)
	}
	if _u.mutation.SignerKeyIDCleared() {
		_spec.ClearField(aarmreceipt.FieldSignerKeyID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aarmreceipt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AarmReceiptUpdateOne is the builder for updating a single AarmReceipt entity.
type AarmReceiptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AarmReceiptMutation
}

// SetSessionID sets the "session_id" field.
func (_u *AarmReceiptUpdateOne) SetSessionID(v uuid.UUID) *AarmReceiptUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableSessionID(v *uuid.UUID) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetActionID sets the "action_id" field.
func (_u *AarmReceiptUpdateOne) SetActionID(v uuid.UUID) *AarmReceiptUpdateOne {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableActionID(v *uuid.UUID) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// ClearActionID clears the value of the "action_id" field.
func (_u *AarmReceiptUpdateOne) ClearActionID() *AarmReceiptUpdateOne {
	_u.mutation.ClearActionID()
	return _u
}

// SetEventID sets the "event_id" field.
func (_u *AarmReceiptUpdateOne) SetEventID(v uuid.UUID) *AarmReceiptUpdateOne {
	_u.mutation.SetEventID(v)
	return _u
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableEventID(v *uuid.UUID) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetEventID(*v)
	}
	return _u
}

// ClearEventID clears the value of the "event_id" field.
func (_u *AarmReceiptUpdateOne) ClearEventID() *AarmReceiptUpdateOne {
	_u.mutation.ClearEventID()
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *AarmReceiptUpdateOne) SetSequence(v int64) *AarmReceiptUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableSequence(v *int64) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *AarmReceiptUpdateOne) AddSequence(v int64) *AarmReceiptUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetAgent sets the "agent" field.
func (_u *AarmReceiptUpdateOne) SetAgent(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetAgent(v)
	return _u
}

// SetNillableAgent sets the "agent" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableAgent(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetAgent(*v)
	}
	return _u
}

// ClearAgent clears the value of the "agent" field.
func (_u *AarmReceiptUpdateOne) ClearAgent() *AarmReceiptUpdateOne {
	_u.mutation.ClearAgent()
	return _u
}

// SetTool sets the "tool" field.
func (_u *AarmReceiptUpdateOne) SetTool(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetTool(v)
	return _u
}

// SetNillableTool sets the "tool" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableTool(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetTool(*v)
	}
	return _u
}

// ClearTool clears the value of the "tool" field.
func (_u *AarmReceiptUpdateOne) ClearTool() *AarmReceiptUpdateOne {
	_u.mutation.ClearTool()
	return _u
}

// SetActionType sets the "action_type" field.
func (_u *AarmReceiptUpdateOne) SetActionType(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetActionType(v)
	return _u
}

// SetNillableActionType sets the "action_type" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableActionType(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetActionType(*v)
	}
	return _u
}

// SetProject sets the "project" field.
func (_u *AarmReceiptUpdateOne) SetProject(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetProject(v)
	return _u
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableProject(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetProject(*v)
	}
	return _u
}

// ClearProject clears the value of the "project" field.
func (_u *AarmReceiptUpdateOne) ClearProject() *AarmReceiptUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// SetDecision sets the "decision" field.
func (_u *AarmReceiptUpdateOne) SetDecision(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetDecision(v)
	return _u
}

// SetNillableDecision sets the "decision" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableDecision(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetDecision(*v)
	}
	return _u
}

// SetMatchedRuleIds sets the "matched_rule_ids" field.
func (_u *AarmReceiptUpdateOne) SetMatchedRuleIds(v []string) *AarmReceiptUpdateOne {
	_u.mutation.SetMatchedRuleIds(v)
	return _u
}

// AppendMatchedRuleIds appends value to the "matched_rule_ids" field.
func (_u *AarmReceiptUpdateOne) AppendMatchedRuleIds(v []string) *AarmReceiptUpdateOne {
	_u.mutation.AppendMatchedRuleIds(v)
	return _u
}

// ClearMatchedRuleIds clears the value of the "matched_rule_ids" field.
func (_u *AarmReceiptUpdateOne) ClearMatchedRuleIds() *AarmReceiptUpdateOne {
	_u.mutation.ClearMatchedRuleIds()
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *AarmReceiptUpdateOne) SetSeverity(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableSeverity(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// ClearSeverity clears the value of the "severity" field.
func (_u *AarmReceiptUpdateOne) ClearSeverity() *AarmReceiptUpdateOne {
	_u.mutation.ClearSeverity()
	return _u
}

// SetMessage sets the "message" field.
func (_u *AarmReceiptUpdateOne) SetMessage(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableMessage(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *AarmReceiptUpdateOne) ClearMessage() *AarmReceiptUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetResultStatus sets the "result_status" field.
func (_u *AarmReceiptUpdateOne) SetResultStatus(v aarmreceipt.ResultStatus) *AarmReceiptUpdateOne {
	_u.mutation.SetResultStatus(v)
	return _u
}

// SetNillableResultStatus sets the "result_status" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableResultStatus(v *aarmreceipt.ResultStatus) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetResultStatus(*v)
	}
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AarmReceiptUpdateOne) SetDurationMs(v int64) *AarmReceiptUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableDurationMs(v *int64) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AarmReceiptUpdateOne) AddDurationMs(v int64) *AarmReceiptUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AarmReceiptUpdateOne) ClearDurationMs() *AarmReceiptUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AarmReceiptUpdateOne) SetErrorMessage(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableErrorMessage(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AarmReceiptUpdateOne) ClearErrorMessage() *AarmReceiptUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *AarmReceiptUpdateOne) SetSnapshot(v map[string]interface{}) *AarmReceiptUpdateOne {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *AarmReceiptUpdateOne) ClearSnapshot() *AarmReceiptUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetActionPayload sets the "action_payload" field.
func (_u *AarmReceiptUpdateOne) SetActionPayload(v map[string]interface{}) *AarmReceiptUpdateOne {
	_u.mutation.SetActionPayload(v)
	return _u
}

// ClearActionPayload clears the value of the "action_payload" field.
func (_u *AarmReceiptUpdateOne) ClearActionPayload() *AarmReceiptUpdateOne {
	_u.mutation.ClearActionPayload()
	return _u
}

// SetPrevHash sets the "prev_hash" field.
func (_u *AarmReceiptUpdateOne) SetPrevHash(v []byte) *AarmReceiptUpdateOne {
	_u.mutation.SetPrevHash(v)
	return _u
}

// ClearPrevHash clears the value of the "prev_hash" field.
func (_u *AarmReceiptUpdateOne) ClearPrevHash() *AarmReceiptUpdateOne {
	_u.mutation.ClearPrevHash()
	return _u
}

// SetHash sets the "hash" field.
func (_u *AarmReceiptUpdateOne) SetHash(v []byte) *AarmReceiptUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetSubagentID sets the "subagent_id" field.
func (_u *AarmReceiptUpdateOne) SetSubagentID(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetSubagentID(v)
	return _u
}

// SetNillableSubagentID sets the "subagent_id" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableSubagentID(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetSubagentID(*v)
	}
	return _u
}

// ClearSubagentID clears the value of the "subagent_id" field.
func (_u *AarmReceiptUpdateOne) ClearSubagentID() *AarmReceiptUpdateOne {
	_u.mutation.ClearSubagentID()
	return _u
}

// SetSubagentType sets the "subagent_type" field.
func (_u *AarmReceiptUpdateOne) SetSubagentType(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetSubagentType(v)
	return _u
}

// SetNillableSubagentType sets the "subagent_type" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableSubagentType(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetSubagentType(*v)
	}
	return _u
}

// ClearSubagentType clears the value of the "subagent_type" field.
func (_u *AarmReceiptUpdateOne) ClearSubagentType() *AarmReceiptUpdateOne {
	_u.mutation.ClearSubagentType()
	return _u
}

// SetPolicyHash sets the "policy_hash" field.
func (_u *AarmReceiptUpdateOne) SetPolicyHash(v []byte) *AarmReceiptUpdateOne {
	_u.mutation.SetPolicyHash(v)
	return _u
}

// ClearPolicyHash clears the value of the "policy_hash" field.
func (_u *AarmReceiptUpdateOne) ClearPolicyHash() *AarmReceiptUpdateOne {
	_u.mutation.ClearPolicyHash()
	return _u
}

// SetSignature sets the "signature" field.
func (_u *AarmReceiptUpdateOne) SetSignature(v []byte) *AarmReceiptUpdateOne {
	_u.mutation.SetSignature(v)
	return _u
}

// ClearSignature clears the value of the "signature" field.
func (_u *AarmReceiptUpdateOne) ClearSignature() *AarmReceiptUpdateOne {
	_u.mutation.ClearSignature()
	return _u
}

// SetSignerKeyID sets the "signer_key_id" field.
func (_u *AarmReceiptUpdateOne) SetSignerKeyID(v string) *AarmReceiptUpdateOne {
	_u.mutation.SetSignerKeyID(v)
	return _u
}

// SetNillableSignerKeyID sets the "signer_key_id" field if the given value is not nil.
func (_u *AarmReceiptUpdateOne) SetNillableSignerKeyID(v *string) *AarmReceiptUpdateOne {
	if v != nil {
		_u.SetSignerKeyID(*v)
	}
	return _u
}

// ClearSignerKeyID clears the value of the "signer_key_id" field.
func (_u *AarmReceiptUpdateOne) ClearSignerKeyID() *AarmReceiptUpdateOne {
	_u.mutation.ClearSignerKeyID()
	return _u
}

// Mutation returns the AarmReceiptMutation object of the builder.
func (_u *AarmReceiptUpdateOne) Mutation() *AarmReceiptMutation {
	return _u.mutation
}

// Where appends a list predicates to the AarmReceiptUpdate builder.
func (_u *AarmReceiptUpdateOne) Where(ps ...predicate.AarmReceipt) *AarmReceiptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AarmReceiptUpdateOne) Select(field string, fields ...string) *AarmReceiptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AarmReceipt entity.
func (_u *AarmReceiptUpdateOne) Save(ctx context.Context) (*AarmReceipt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AarmReceiptUpdateOne) SaveX(ctx context.Context) *AarmReceipt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AarmReceiptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AarmReceiptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AarmReceiptUpdateOne) check() error {
	if v, ok := _u.mutation.Sequence(); ok {
		if err := aarmreceipt.SequenceValidator(v); err != nil {
			return &ValidationError{Name: "sequence", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.sequence": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResultStatus(); ok {
		if err := aarmreceipt.ResultStatusValidator(v); err != nil {
			return &ValidationError{Name: "result_status", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.result_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrevHash(); ok {
		if err := aarmreceipt.PrevHashValidator(v); err != nil {
			return &ValidationError{Name: "prev_hash", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.prev_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := aarmreceipt.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PolicyHash(); ok {
		if err := aarmreceipt.PolicyHashValidator(v); err != nil {
			return &ValidationError{Name: "policy_hash", err: fmt.Errorf(`ent: validator failed for field "AarmReceipt.policy_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AarmReceiptUpdateOne) sqlSave(ctx context.Context) (_node *AarmReceipt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(aarmreceipt.Table, aarmreceipt.Columns, sqlgraph.NewFieldSpec(aarmreceipt.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AarmReceipt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, aarmreceipt.FieldID)
		for _, f := range fields {
			if !aarmreceipt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != aarmreceipt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(aarmreceipt.FieldSessionID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ActionID(); ok {
		_spec.SetField(aarmreceipt.FieldActionID, field.TypeUUID, value)
	}
	if _u.mutation.ActionIDCleared() {
		_spec.ClearField(aarmreceipt.FieldActionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.EventID(); ok {
		_spec.SetField(aarmreceipt.FieldEventID, field.TypeUUID, value)
	}
	if _u.mutation.EventIDCleared() {
		_spec.ClearField(aarmreceipt.FieldEventID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(aarmreceipt.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(aarmreceipt.FieldSequence, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Agent(); ok {
		_spec.SetField(aarmreceipt.FieldAgent, field.TypeString, value)
	}
	if _u.mutation.AgentCleared() {
		_spec.ClearField(aarmreceipt.FieldAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Tool(); ok {
		_spec.SetField(aarmreceipt.FieldTool, field.TypeString, value)
	}
	if _u.mutation.ToolCleared() {
		_spec.ClearField(aarmreceipt.FieldTool, field.TypeString)
	}
	if value, ok := _u.mutation.ActionType(); ok {
		_spec.SetField(aarmreceipt.FieldActionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Project(); ok {
		_spec.SetField(aarmreceipt.FieldProject, field.TypeString, value)
	}
	if _u.mutation.ProjectCleared() {
		_spec.ClearField(aarmreceipt.FieldProject, field.TypeString)
	}
	if value, ok := _u.mutation.Decision(); ok {
		_spec.SetField(aarmreceipt.FieldDecision, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedRuleIds(); ok {
		_spec.SetField(aarmreceipt.FieldMatchedRuleIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMatchedRuleIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, aarmreceipt.FieldMatchedRuleIds, value)
		})
	}
	if _u.mutation.MatchedRuleIdsCleared() {
		_spec.ClearField(aarmreceipt.FieldMatchedRuleIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(aarmreceipt.FieldSeverity, field.TypeString, value)
	}
	if _u.mutation.SeverityCleared() {
		_spec.ClearField(aarmreceipt.FieldSeverity, field.TypeString)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(aarmreceipt.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(aarmreceipt.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ResultStatus(); ok {
		_spec.SetField(aarmreceipt.FieldResultStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(aarmreceipt.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(aarmreceipt.FieldDurationMs, field.TypeInt64, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(aarmreceipt.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(aarmreceipt.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(aarmreceipt.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(aarmreceipt.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(aarmreceipt.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActionPayload(); ok {
		_spec.SetField(aarmreceipt.FieldActionPayload, field.TypeJSON, value)
	}
	if _u.mutation.ActionPayloadCleared() {
		_spec.ClearField(aarmreceipt.FieldActionPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.PrevHash(); ok {
		_spec.SetField(aarmreceipt.FieldPrevHash, field.TypeBytes, value)
	}
	if _u.mutation.PrevHashCleared() {
		_spec.ClearField(aarmreceipt.FieldPrevHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(aarmreceipt.FieldHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.SubagentID(); ok {
		_spec.SetField(aarmreceipt.FieldSubagentID, field.TypeString, value)
	}
	if _u.mutation.SubagentIDCleared() {
		_spec.ClearField(aarmreceipt.FieldSubagentID, field.TypeString)
	}
	if value, ok := _u.mutation.SubagentType(); ok {
		_spec.SetField(aarmreceipt.FieldSubagentType, field.TypeString, value)
	}
	if _u.mutation.SubagentTypeCleared() {
		_spec.ClearField(aarmreceipt.FieldSubagentType, field.TypeString)
	}
	if value, ok := _u.mutation.PolicyHash(); ok {
		_spec.SetField(aarmreceipt.FieldPolicyHash, field.TypeBytes, value)
	}
	if _u.mutation.PolicyHashCleared() {
		_spec.ClearField(aarmreceipt.FieldPolicyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(aarmreceipt.FieldSignature, field.TypeBytes, value)
	}
	if _u.mutation.SignatureCleared() {
		_spec.ClearField(aarmreceipt.FieldSignature, field.TypeBytes)
	}
	if value, ok := _u.mutation.SignerKeyID(); ok {
		_spec.SetField(aarmreceipt.FieldSignerKeyID, field.TypeString, value)
	}
	if _u.mutation.SignerKeyIDCleared() {
		_spec.ClearField(aarmreceipt.FieldSignerKeyID, field.TypeString)
	}
	_node = &AarmReceipt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{aarmreceipt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
