// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/aarmapprovalrequest"
)

// AarmApprovalRequestCreate is the builder for creating a AarmApprovalRequest entity.
type AarmApprovalRequestCreate struct {
	config
	mutation *AarmApprovalRequestMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *AarmApprovalRequestCreate) SetSessionID(v uuid.UUID) *AarmApprovalRequestCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetActionID sets the "action_id" field.
func (_c *AarmApprovalRequestCreate) SetActionID(v uuid.UUID) *AarmApprovalRequestCreate {
	_c.mutation.SetActionID(v)
	return _c
}

// SetReceiptSequence sets the "receipt_sequence" field.
func (_c *AarmApprovalRequestCreate) SetReceiptSequence(v int64) *AarmApprovalRequestCreate {
	_c.mutation.SetReceiptSequence(v)
	return _c
}

// SetActionDigest sets the "action_digest" field.
func (_c *AarmApprovalRequestCreate) SetActionDigest(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetActionDigest(v)
	return _c
}

// SetRuleIds sets the "rule_ids" field.
func (_c *AarmApprovalRequestCreate) SetRuleIds(v []string) *AarmApprovalRequestCreate {
	_c.mutation.SetRuleIds(v)
	return _c
}

// SetRequester sets the "requester" field.
func (_c *AarmApprovalRequestCreate) SetRequester(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetRequester(v)
	return _c
}

// SetNillableRequester sets the "requester" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableRequester(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetRequester(*v)
	}
	return _c
}

// SetHost sets the "host" field.
func (_c *AarmApprovalRequestCreate) SetHost(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableHost(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetAgent sets the "agent" field.
func (_c *AarmApprovalRequestCreate) SetAgent(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetAgent(v)
	return _c
}

// SetNillableAgent sets the "agent" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableAgent(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetAgent(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *AarmApprovalRequestCreate) SetSummary(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableSummary(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetProject sets the "project" field.
func (_c *AarmApprovalRequestCreate) SetProject(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetProject(v)
	return _c
}

// SetNillableProject sets the "project" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableProject(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetProject(*v)
	}
	return _c
}

// SetMinAssurance sets the "min_assurance" field.
func (_c *AarmApprovalRequestCreate) SetMinAssurance(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetMinAssurance(v)
	return _c
}

// SetNillableMinAssurance sets the "min_assurance" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableMinAssurance(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetMinAssurance(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *AarmApprovalRequestCreate) SetState(v aarmapprovalrequest.State) *AarmApprovalRequestCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableState(v *aarmapprovalrequest.State) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetRequestedAt sets the "requested_at" field.
func (_c *AarmApprovalRequestCreate) SetRequestedAt(v time.Time) *AarmApprovalRequestCreate {
	_c.mutation.SetRequestedAt(v)
	return _c
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableRequestedAt(v *time.Time) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetRequestedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AarmApprovalRequestCreate) SetExpiresAt(v time.Time) *AarmApprovalRequestCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetInline sets the "inline" field.
func (_c *AarmApprovalRequestCreate) SetInline(v bool) *AarmApprovalRequestCreate {
	_c.mutation.SetInline(v)
	return _c
}

// SetNillableInline sets the "inline" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableInline(v *bool) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetInline(*v)
	}
	return _c
}

// SetReview sets the "review" field.
func (_c *AarmApprovalRequestCreate) SetReview(v bool) *AarmApprovalRequestCreate {
	_c.mutation.SetReview(v)
	return _c
}

// SetNillableReview sets the "review" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableReview(v *bool) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetReview(*v)
	}
	return _c
}

// SetRequesterAudit sets the "requester_audit" field.
func (_c *AarmApprovalRequestCreate) SetRequesterAudit(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetRequesterAudit(v)
	return _c
}

// SetNillableRequesterAudit sets the "requester_audit" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableRequesterAudit(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetRequesterAudit(*v)
	}
	return _c
}

// SetDecidedAt sets the "decided_at" field.
func (_c *AarmApprovalRequestCreate) SetDecidedAt(v time.Time) *AarmApprovalRequestCreate {
	_c.mutation.SetDecidedAt(v)
	return _c
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableDecidedAt(v *time.Time) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetDecidedAt(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *AarmApprovalRequestCreate) SetChannel(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableChannel(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetChannel(*v)
	}
	return _c
}

// SetAssurance sets the "assurance" field.
func (_c *AarmApprovalRequestCreate) SetAssurance(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetAssurance(v)
	return _c
}

// SetNillableAssurance sets the "assurance" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableAssurance(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetAssurance(*v)
	}
	return _c
}

// SetApprover sets the "approver" field.
func (_c *AarmApprovalRequestCreate) SetApprover(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetApprover(v)
	return _c
}

// SetNillableApprover sets the "approver" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableApprover(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetApprover(*v)
	}
	return _c
}

// SetPeerTrust sets the "peer_trust" field.
func (_c *AarmApprovalRequestCreate) SetPeerTrust(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetPeerTrust(v)
	return _c
}

// SetNillablePeerTrust sets the "peer_trust" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillablePeerTrust(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetPeerTrust(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *AarmApprovalRequestCreate) SetNote(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableNote(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *AarmApprovalRequestCreate) SetScope(v string) *AarmApprovalRequestCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableScope(v *string) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *AarmApprovalRequestCreate) SetNotifiedAt(v time.Time) *AarmApprovalRequestCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableNotifiedAt(v *time.Time) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AarmApprovalRequestCreate) SetID(v uuid.UUID) *AarmApprovalRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AarmApprovalRequestCreate) SetNillableID(v *uuid.UUID) *AarmApprovalRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AarmApprovalRequestMutation object of the builder.
func (_c *AarmApprovalRequestCreate) Mutation() *AarmApprovalRequestMutation {
	return _c.mutation
}

// Save creates the AarmApprovalRequest in the database.
func (_c *AarmApprovalRequestCreate) Save(ctx context.Context) (*AarmApprovalRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AarmApprovalRequestCreate) SaveX(ctx context.Context) *AarmApprovalRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AarmApprovalRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AarmApprovalRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AarmApprovalRequestCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := aarmapprovalrequest.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		v := aarmapprovalrequest.DefaultRequestedAt()
		_c.mutation.SetRequestedAt(v)
	}
	if _, ok := _c.mutation.Inline(); !ok {
		v := aarmapprovalrequest.DefaultInline
		_c.mutation.SetInline(v)
	}
	if _, ok := _c.mutation.Review(); !ok {
		v := aarmapprovalrequest.DefaultReview
		_c.mutation.SetReview(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := aarmapprovalrequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AarmApprovalRequestCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AarmApprovalRequest.session_id"`)}
	}
	if _, ok := _c.mutation.ActionID(); !ok {
		return &ValidationError{Name: "action_id", err: errors.New(`ent: missing required field "AarmApprovalRequest.action_id"`)}
	}
	if _, ok := _c.mutation.ReceiptSequence(); !ok {
		return &ValidationError{Name: "receipt_sequence", err: errors.New(`ent: missing required field "AarmApprovalRequest.receipt_sequence"`)}
	}
	if v, ok := _c.mutation.ReceiptSequence(); ok {
		if err := aarmapprovalrequest.ReceiptSequenceValidator(v); err != nil {
			return &ValidationError{Name: "receipt_sequence", err: fmt.Errorf(`ent: validator failed for field "AarmApprovalRequest.receipt_sequence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionDigest(); !ok {
		return &ValidationError{Name: "action_digest", err: errors.New(`ent: missing required field "AarmApprovalRequest.action_digest"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "AarmApprovalRequest.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := aarmapprovalrequest.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "AarmApprovalRequest.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "AarmApprovalRequest.requested_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AarmApprovalRequest.expires_at"`)}
	}
	if _, ok := _c.mutation.Inline(); !ok {
		return &ValidationError{Name: "inline", err: errors.New(`ent: missing required field "AarmApprovalRequest.inline"`)}
	}
	if _, ok := _c.mutation.Review(); !ok {
		return &ValidationError{Name: "review", err: errors.New(`ent: missing required field "AarmApprovalRequest.review"`)}
	}
	return nil
}

func (_c *AarmApprovalRequestCreate) sqlSave(ctx context.Context) (*AarmApprovalRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AarmApprovalRequestCreate) createSpec() (*AarmApprovalRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &AarmApprovalRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aarmapprovalrequest.Table, sqlgraph.NewFieldSpec(aarmapprovalrequest.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(aarmapprovalrequest.FieldSessionID, field.TypeUUID, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.ActionID(); ok {
		_spec.SetField(aarmapprovalrequest.FieldActionID, field.TypeUUID, value)
		_node.ActionID = value
	}
	if value, ok := _c.mutation.ReceiptSequence(); ok {
		_spec.SetField(aarmapprovalrequest.FieldReceiptSequence, field.TypeInt64, value)
		_node.ReceiptSequence = value
	}
	if value, ok := _c.mutation.ActionDigest(); ok {
		_spec.SetField(aarmapprovalrequest.FieldActionDigest, field.TypeString, value)
		_node.ActionDigest = value
	}
	if value, ok := _c.mutation.RuleIds(); ok {
		_spec.SetField(aarmapprovalrequest.FieldRuleIds, field.TypeJSON, value)
		_node.RuleIds = value
	}
	if value, ok := _c.mutation.Requester(); ok {
		_spec.SetField(aarmapprovalrequest.FieldRequester, field.TypeString, value)
		_node.Requester = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(aarmapprovalrequest.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Agent(); ok {
		_spec.SetField(aarmapprovalrequest.FieldAgent, field.TypeString, value)
		_node.Agent = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(aarmapprovalrequest.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Project(); ok {
		_spec.SetField(aarmapprovalrequest.FieldProject, field.TypeString, value)
		_node.Project = value
	}
	if value, ok := _c.mutation.MinAssurance(); ok {
		_spec.SetField(aarmapprovalrequest.FieldMinAssurance, field.TypeString, value)
		_node.MinAssurance = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(aarmapprovalrequest.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.RequestedAt(); ok {
		_spec.SetField(aarmapprovalrequest.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(aarmapprovalrequest.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Inline(); ok {
		_spec.SetField(aarmapprovalrequest.FieldInline, field.TypeBool, value)
		_node.Inline = value
	}
	if value, ok := _c.mutation.Review(); ok {
		_spec.SetField(aarmapprovalrequest.FieldReview, field.TypeBool, value)
		_node.Review = value
	}
	if value, ok := _c.mutation.RequesterAudit(); ok {
		_spec.SetField(aarmapprovalrequest.FieldRequesterAudit, field.TypeString, value)
		_node.RequesterAudit = value
	}
	if value, ok := _c.mutation.DecidedAt(); ok {
		_spec.SetField(aarmapprovalrequest.FieldDecidedAt, field.TypeTime, value)
		_node.DecidedAt = &value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(aarmapprovalrequest.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.Assurance(); ok {
		_spec.SetField(aarmapprovalrequest.FieldAssurance, field.TypeString, value)
		_node.Assurance = value
	}
	if value, ok := _c.mutation.Approver(); ok {
		_spec.SetField(aarmapprovalrequest.FieldApprover, field.TypeString, value)
		_node.Approver = value
	}
	if value, ok := _c.mutation.PeerTrust(); ok {
		_spec.SetField(aarmapprovalrequest.FieldPeerTrust, field.TypeString, value)
		_node.PeerTrust = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(aarmapprovalrequest.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(aarmapprovalrequest.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(aarmapprovalrequest.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = &value
	}
	return _node, _spec
}

// AarmApprovalRequestCreateBulk is the builder for creating many AarmApprovalRequest entities in bulk.
type AarmApprovalRequestCreateBulk struct {
	config
	err      error
	builders []*AarmApprovalRequestCreate
}

// Save creates the AarmApprovalRequest entities in the database.
func (_c *AarmApprovalRequestCreateBulk) Save(ctx context.Context) ([]*AarmApprovalRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AarmApprovalRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AarmApprovalRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AarmApprovalRequestCreateBulk) SaveX(ctx context.Context) []*AarmApprovalRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AarmApprovalRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AarmApprovalRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
