// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/aarmdeferredaction"
)

// AarmDeferredActionCreate is the builder for creating a AarmDeferredAction entity.
type AarmDeferredActionCreate struct {
	config
	mutation *AarmDeferredActionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *AarmDeferredActionCreate) SetSessionID(v uuid.UUID) *AarmDeferredActionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetReceiptSequence sets the "receipt_sequence" field.
func (_c *AarmDeferredActionCreate) SetReceiptSequence(v int64) *AarmDeferredActionCreate {
	_c.mutation.SetReceiptSequence(v)
	return _c
}

// SetActionID sets the "action_id" field.
func (_c *AarmDeferredActionCreate) SetActionID(v uuid.UUID) *AarmDeferredActionCreate {
	_c.mutation.SetActionID(v)
	return _c
}

// SetDeferredAt sets the "deferred_at" field.
func (_c *AarmDeferredActionCreate) SetDeferredAt(v time.Time) *AarmDeferredActionCreate {
	_c.mutation.SetDeferredAt(v)
	return _c
}

// SetNillableDeferredAt sets the "deferred_at" field if the given value is not nil.
func (_c *AarmDeferredActionCreate) SetNillableDeferredAt(v *time.Time) *AarmDeferredActionCreate {
	if v != nil {
		_c.SetDeferredAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AarmDeferredActionCreate) SetExpiresAt(v time.Time) *AarmDeferredActionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *AarmDeferredActionCreate) SetReason(v string) *AarmDeferredActionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AarmDeferredActionCreate) SetStatus(v aarmdeferredaction.Status) *AarmDeferredActionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AarmDeferredActionCreate) SetNillableStatus(v *aarmdeferredaction.Status) *AarmDeferredActionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *AarmDeferredActionCreate) SetResolvedAt(v time.Time) *AarmDeferredActionCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *AarmDeferredActionCreate) SetNillableResolvedAt(v *time.Time) *AarmDeferredActionCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// SetResolver sets the "resolver" field.
func (_c *AarmDeferredActionCreate) SetResolver(v string) *AarmDeferredActionCreate {
	_c.mutation.SetResolver(v)
	return _c
}

// SetNillableResolver sets the "resolver" field if the given value is not nil.
func (_c *AarmDeferredActionCreate) SetNillableResolver(v *string) *AarmDeferredActionCreate {
	if v != nil {
		_c.SetResolver(*v)
	}
	return _c
}

// SetResolutionNote sets the "resolution_note" field.
func (_c *AarmDeferredActionCreate) SetResolutionNote(v string) *AarmDeferredActionCreate {
	_c.mutation.SetResolutionNote(v)
	return _c
}

// SetNillableResolutionNote sets the "resolution_note" field if the given value is not nil.
func (_c *AarmDeferredActionCreate) SetNillableResolutionNote(v *string) *AarmDeferredActionCreate {
	if v != nil {
		_c.SetResolutionNote(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AarmDeferredActionCreate) SetID(v uuid.UUID) *AarmDeferredActionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AarmDeferredActionCreate) SetNillableID(v *uuid.UUID) *AarmDeferredActionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AarmDeferredActionMutation object of the builder.
func (_c *AarmDeferredActionCreate) Mutation() *AarmDeferredActionMutation {
	return _c.mutation
}

// Save creates the AarmDeferredAction in the database.
func (_c *AarmDeferredActionCreate) Save(ctx context.Context) (*AarmDeferredAction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AarmDeferredActionCreate) SaveX(ctx context.Context) *AarmDeferredAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AarmDeferredActionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AarmDeferredActionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AarmDeferredActionCreate) defaults() {
	if _, ok := _c.mutation.DeferredAt(); !ok {
		v := aarmdeferredaction.DefaultDeferredAt()
		_c.mutation.SetDeferredAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := aarmdeferredaction.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := aarmdeferredaction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AarmDeferredActionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AarmDeferredAction.session_id"`)}
	}
	if _, ok := _c.mutation.ReceiptSequence(); !ok {
		return &ValidationError{Name: "receipt_sequence", err: errors.New(`ent: missing required field "AarmDeferredAction.receipt_sequence"`)}
	}
	if v, ok := _c.mutation.ReceiptSequence(); ok {
		if err := aarmdeferredaction.ReceiptSequenceValidator(v); err != nil {
			return &ValidationError{Name: "receipt_sequence", err: fmt.Errorf(`ent: validator failed for field "AarmDeferredAction.receipt_sequence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionID(); !ok {
		return &ValidationError{Name: "action_id", err: errors.New(`ent: missing required field "AarmDeferredAction.action_id"`)}
	}
	if _, ok := _c.mutation.DeferredAt(); !ok {
		return &ValidationError{Name: "deferred_at", err: errors.New(`ent: missing required field "AarmDeferredAction.deferred_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AarmDeferredAction.expires_at"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "AarmDeferredAction.reason"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AarmDeferredAction.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := aarmdeferredaction.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AarmDeferredAction.status": %w`, err)}
		}
	}
	return nil
}

func (_c *AarmDeferredActionCreate) sqlSave(ctx context.Context) (*AarmDeferredAction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AarmDeferredActionCreate) createSpec() (*AarmDeferredAction, *sqlgraph.CreateSpec) {
	var (
		_node = &AarmDeferredAction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aarmdeferredaction.Table, sqlgraph.NewFieldSpec(aarmdeferredaction.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(aarmdeferredaction.FieldSessionID, field.TypeUUID, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.ReceiptSequence(); ok {
		_spec.SetField(aarmdeferredaction.FieldReceiptSequence, field.TypeInt64, value)
		_node.ReceiptSequence = value
	}
	if value, ok := _c.mutation.ActionID(); ok {
		_spec.SetField(aarmdeferredaction.FieldActionID, field.TypeUUID, value)
		_node.ActionID = value
	}
	if value, ok := _c.mutation.DeferredAt(); ok {
		_spec.SetField(aarmdeferredaction.FieldDeferredAt, field.TypeTime, value)
		_node.DeferredAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(aarmdeferredaction.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(aarmdeferredaction.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(aarmdeferredaction.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(aarmdeferredaction.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	if value, ok := _c.mutation.Resolver(); ok {
		_spec.SetField(aarmdeferredaction.FieldResolver, field.TypeString, value)
		_node.Resolver = value
	}
	if value, ok := _c.mutation.ResolutionNote(); ok {
		_spec.SetField(aarmdeferredaction.FieldResolutionNote, field.TypeString, value)
		_node.ResolutionNote = value
	}
	return _node, _spec
}

// AarmDeferredActionCreateBulk is the builder for creating many AarmDeferredAction entities in bulk.
type AarmDeferredActionCreateBulk struct {
	config
	err      error
	builders []*AarmDeferredActionCreate
}

// Save creates the AarmDeferredAction entities in the database.
func (_c *AarmDeferredActionCreateBulk) Save(ctx context.Context) ([]*AarmDeferredAction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AarmDeferredAction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AarmDeferredActionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AarmDeferredActionCreateBulk) SaveX(ctx context.Context) []*AarmDeferredAction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AarmDeferredActionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AarmDeferredActionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
