// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/gryph/storage/ent/aarmapprovalrequest"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// AarmApprovalRequestDelete is the builder for deleting a AarmApprovalRequest entity.
type AarmApprovalRequestDelete struct {
	config
	hooks    []Hook
	mutation *AarmApprovalRequestMutation
}

// Where appends a list predicates to the AarmApprovalRequestDelete builder.
func (_d *AarmApprovalRequestDelete) Where(ps ...predicate.AarmApprovalRequest) *AarmApprovalRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AarmApprovalRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AarmApprovalRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AarmApprovalRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(aarmapprovalrequest.Table, sqlgraph.NewFieldSpec(aarmapprovalrequest.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AarmApprovalRequestDeleteOne is the builder for deleting a single AarmApprovalRequest entity.
type AarmApprovalRequestDeleteOne struct {
	_d *AarmApprovalRequestDelete
}

// Where appends a list predicates to the AarmApprovalRequestDelete builder.
func (_d *AarmApprovalRequestDeleteOne) Where(ps ...predicate.AarmApprovalRequest) *AarmApprovalRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AarmApprovalRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{aarmapprovalrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AarmApprovalRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
