// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/aarmdeferredaction"
)

// AarmDeferredAction is the model entity for the AarmDeferredAction schema.
type AarmDeferredAction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// ReceiptSequence holds the value of the "receipt_sequence" field.
	ReceiptSequence int64 `json:"receipt_sequence,omitempty"`
	// ActionID holds the value of the "action_id" field.
	ActionID uuid.UUID `json:"action_id,omitempty"`
	// DeferredAt holds the value of the "deferred_at" field.
	DeferredAt time.Time `json:"deferred_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status aarmdeferredaction.Status `json:"status,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// Resolver holds the value of the "resolver" field.
	Resolver string `json:"resolver,omitempty"`
	// ResolutionNote holds the value of the "resolution_note" field.
	ResolutionNote string `json:"resolution_note,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AarmDeferredAction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case aarmdeferredaction.FieldReceiptSequence:
			values[i] = new(sql.NullInt64)
		case aarmdeferredaction.FieldReason, aarmdeferredaction.FieldStatus, aarmdeferredaction.FieldResolver, aarmdeferredaction.FieldResolutionNote:
			values[i] = new(sql.NullString)
		case aarmdeferredaction.FieldDeferredAt, aarmdeferredaction.FieldExpiresAt, aarmdeferredaction.FieldResolvedAt:
			values[i] = new(sql.NullTime)
		case aarmdeferredaction.FieldID, aarmdeferredaction.FieldSessionID, aarmdeferredaction.FieldActionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AarmDeferredAction fields.
func (_m *AarmDeferredAction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case aarmdeferredaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case aarmdeferredaction.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case aarmdeferredaction.FieldReceiptSequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field receipt_sequence", values[i])
			} else if value.Valid {
				_m.ReceiptSequence = value.Int64
			}
		case aarmdeferredaction.FieldActionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field action_id", values[i])
			} else if value != nil {
				_m.ActionID = *value
			}
		case aarmdeferredaction.FieldDeferredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deferred_at", values[i])
			} else if value.Valid {
				_m.DeferredAt = value.Time
			}
		case aarmdeferredaction.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case aarmdeferredaction.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case aarmdeferredaction.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = aarmdeferredaction.Status(value.String)
			}
		case aarmdeferredaction.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case aarmdeferredaction.FieldResolver:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolver", values[i])
			} else if value.Valid {
				_m.Resolver = value.String
			}
		case aarmdeferredaction.FieldResolutionNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution_note", values[i])
			} else if value.Valid {
				_m.ResolutionNote = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AarmDeferredAction.
// This includes values selected through modifiers, order, etc.
func (_m *AarmDeferredAction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AarmDeferredAction.
// Note that you need to call AarmDeferredAction.Unwrap() before calling this method if this AarmDeferredAction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AarmDeferredAction) Update() *AarmDeferredActionUpdateOne {
	return NewAarmDeferredActionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AarmDeferredAction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AarmDeferredAction) Unwrap() *AarmDeferredAction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AarmDeferredAction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AarmDeferredAction) String() string {
	var builder strings.Builder
	builder.WriteString("AarmDeferredAction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("receipt_sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReceiptSequence))
	builder.WriteString(", ")
	builder.WriteString("action_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionID))
	builder.WriteString(", ")
	builder.WriteString("deferred_at=")
	builder.WriteString(_m.DeferredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("resolver=")
	builder.WriteString(_m.Resolver)
	builder.WriteString(", ")
	builder.WriteString("resolution_note=")
	builder.WriteString(_m.ResolutionNote)
	builder.WriteByte(')')
	return builder.String()
}

// AarmDeferredActions is a parsable slice of AarmDeferredAction.
type AarmDeferredActions []*AarmDeferredAction
