// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/safedep/gryph/storage/ent/auditstreamcursor"
)

// AuditStreamCursor is the model entity for the AuditStreamCursor schema.
type AuditStreamCursor struct {
	config `json:"-"`
	// ID of the ent.
	// target_name used as primary key
	ID string `json:"id,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt time.Time `json:"last_synced_at,omitempty"`
	// LastID holds the value of the "last_id" field.
	LastID       string `json:"last_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuditStreamCursor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case auditstreamcursor.FieldID, auditstreamcursor.FieldLastID:
			values[i] = new(sql.NullString)
		case auditstreamcursor.FieldLastSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuditStreamCursor fields.
func (_m *AuditStreamCursor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case auditstreamcursor.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case auditstreamcursor.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = value.Time
			}
		case auditstreamcursor.FieldLastID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_id", values[i])
			} else if value.Valid {
				_m.LastID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuditStreamCursor.
// This includes values selected through modifiers, order, etc.
func (_m *AuditStreamCursor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuditStreamCursor.
// Note that you need to call AuditStreamCursor.Unwrap() before calling this method if this AuditStreamCursor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuditStreamCursor) Update() *AuditStreamCursorUpdateOne {
	return NewAuditStreamCursorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuditStreamCursor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuditStreamCursor) Unwrap() *AuditStreamCursor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuditStreamCursor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuditStreamCursor) String() string {
	var builder strings.Builder
	builder.WriteString("AuditStreamCursor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("last_synced_at=")
	builder.WriteString(_m.LastSyncedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_id=")
	builder.WriteString(_m.LastID)
	builder.WriteByte(')')
	return builder.String()
}

// AuditStreamCursors is a parsable slice of AuditStreamCursor.
type AuditStreamCursors []*AuditStreamCursor
