// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/gryph/storage/ent/auditstreamcursor"
)

// AuditStreamCursorCreate is the builder for creating a AuditStreamCursor entity.
type AuditStreamCursorCreate struct {
	config
	mutation *AuditStreamCursorMutation
	hooks    []Hook
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *AuditStreamCursorCreate) SetLastSyncedAt(v time.Time) *AuditStreamCursorCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *AuditStreamCursorCreate) SetNillableLastSyncedAt(v *time.Time) *AuditStreamCursorCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetLastID sets the "last_id" field.
func (_c *AuditStreamCursorCreate) SetLastID(v string) *AuditStreamCursorCreate {
	_c.mutation.SetLastID(v)
	return _c
}

// SetNillableLastID sets the "last_id" field if the given value is not nil.
func (_c *AuditStreamCursorCreate) SetNillableLastID(v *string) *AuditStreamCursorCreate {
	if v != nil {
		_c.SetLastID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditStreamCursorCreate) SetID(v string) *AuditStreamCursorCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuditStreamCursorMutation object of the builder.
func (_c *AuditStreamCursorCreate) Mutation() *AuditStreamCursorMutation {
	return _c.mutation
}

// Save creates the AuditStreamCursor in the database.
func (_c *AuditStreamCursorCreate) Save(ctx context.Context) (*AuditStreamCursor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditStreamCursorCreate) SaveX(ctx context.Context) *AuditStreamCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditStreamCursorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditStreamCursorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditStreamCursorCreate) defaults() {
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		v := auditstreamcursor.DefaultLastSyncedAt()
		_c.mutation.SetLastSyncedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditStreamCursorCreate) check() error {
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "AuditStreamCursor.last_synced_at"`)}
	}
	return nil
}

func (_c *AuditStreamCursorCreate) sqlSave(ctx context.Context) (*AuditStreamCursor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuditStreamCursor.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditStreamCursorCreate) createSpec() (*AuditStreamCursor, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditStreamCursor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditstreamcursor.Table, sqlgraph.NewFieldSpec(auditstreamcursor.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(auditstreamcursor.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	if value, ok := _c.mutation.LastID(); ok {
		_spec.SetField(auditstreamcursor.FieldLastID, field.TypeString, value)
		_node.LastID = value
	}
	return _node, _spec
}

// AuditStreamCursorCreateBulk is the builder for creating many AuditStreamCursor entities in bulk.
type AuditStreamCursorCreateBulk struct {
	config
	err      error
	builders []*AuditStreamCursorCreate
}

// Save creates the AuditStreamCursor entities in the database.
func (_c *AuditStreamCursorCreateBulk) Save(ctx context.Context) ([]*AuditStreamCursor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditStreamCursor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditStreamCursorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditStreamCursorCreateBulk) SaveX(ctx context.Context) []*AuditStreamCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditStreamCursorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditStreamCursorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
