// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/safedep/gryph/storage/ent/aarmdeferredaction"
	"github.com/safedep/gryph/storage/ent/aarmreceipt"
	"github.com/safedep/gryph/storage/ent/auditevent"
	"github.com/safedep/gryph/storage/ent/auditstreamcursor"
	"github.com/safedep/gryph/storage/ent/contextentry"
	"github.com/safedep/gryph/storage/ent/contextstate"
	"github.com/safedep/gryph/storage/ent/eventstreamcursor"
	"github.com/safedep/gryph/storage/ent/selfaudit"
	"github.com/safedep/gryph/storage/ent/session"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AarmDeferredAction is the client for interacting with the AarmDeferredAction builders.
	AarmDeferredAction *AarmDeferredActionClient
	// AarmReceipt is the client for interacting with the AarmReceipt builders.
	AarmReceipt *AarmReceiptClient
	// AuditEvent is the client for interacting with the AuditEvent builders.
	AuditEvent *AuditEventClient
	// AuditStreamCursor is the client for interacting with the AuditStreamCursor builders.
	AuditStreamCursor *AuditStreamCursorClient
	// ContextEntry is the client for interacting with the ContextEntry builders.
	ContextEntry *ContextEntryClient
	// ContextState is the client for interacting with the ContextState builders.
	ContextState *ContextStateClient
	// EventStreamCursor is the client for interacting with the EventStreamCursor builders.
	EventStreamCursor *EventStreamCursorClient
	// SelfAudit is the client for interacting with the SelfAudit builders.
	SelfAudit *SelfAuditClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AarmDeferredAction = NewAarmDeferredActionClient(c.config)
	c.AarmReceipt = NewAarmReceiptClient(c.config)
	c.AuditEvent = NewAuditEventClient(c.config)
	c.AuditStreamCursor = NewAuditStreamCursorClient(c.config)
	c.ContextEntry = NewContextEntryClient(c.config)
	c.ContextState = NewContextStateClient(c.config)
	c.EventStreamCursor = NewEventStreamCursorClient(c.config)
	c.SelfAudit = NewSelfAuditClient(c.config)
	c.Session = NewSessionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		AarmDeferredAction: NewAarmDeferredActionClient(cfg),
		AarmReceipt:        NewAarmReceiptClient(cfg),
		AuditEvent:         NewAuditEventClient(cfg),
		AuditStreamCursor:  NewAuditStreamCursorClient(cfg),
		ContextEntry:       NewContextEntryClient(cfg),
		ContextState:       NewContextStateClient(cfg),
		EventStreamCursor:  NewEventStreamCursorClient(cfg),
		SelfAudit:          NewSelfAuditClient(cfg),
		Session:            NewSessionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		AarmDeferredAction: NewAarmDeferredActionClient(cfg),
		AarmReceipt:        NewAarmReceiptClient(cfg),
		AuditEvent:         NewAuditEventClient(cfg),
		AuditStreamCursor:  NewAuditStreamCursorClient(cfg),
		ContextEntry:       NewContextEntryClient(cfg),
		ContextState:       NewContextStateClient(cfg),
		EventStreamCursor:  NewEventStreamCursorClient(cfg),
		SelfAudit:          NewSelfAuditClient(cfg),
		Session:            NewSessionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AarmDeferredAction.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AarmDeferredAction, c.AarmReceipt, c.AuditEvent, c.AuditStreamCursor,
		c.ContextEntry, c.ContextState, c.EventStreamCursor, c.SelfAudit, c.Session,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AarmDeferredAction, c.AarmReceipt, c.AuditEvent, c.AuditStreamCursor,
		c.ContextEntry, c.ContextState, c.EventStreamCursor, c.SelfAudit, c.Session,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AarmDeferredActionMutation:
		return c.AarmDeferredAction.mutate(ctx, m)
	case *AarmReceiptMutation:
		return c.AarmReceipt.mutate(ctx, m)
	case *AuditEventMutation:
		return c.AuditEvent.mutate(ctx, m)
	case *AuditStreamCursorMutation:
		return c.AuditStreamCursor.mutate(ctx, m)
	case *ContextEntryMutation:
		return c.ContextEntry.mutate(ctx, m)
	case *ContextStateMutation:
		return c.ContextState.mutate(ctx, m)
	case *EventStreamCursorMutation:
		return c.EventStreamCursor.mutate(ctx, m)
	case *SelfAuditMutation:
		return c.SelfAudit.mutate(ctx, m)
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AarmDeferredActionClient is a client for the AarmDeferredAction schema.
type AarmDeferredActionClient struct {
	config
}

// NewAarmDeferredActionClient returns a client for the AarmDeferredAction from the given config.
func NewAarmDeferredActionClient(c config) *AarmDeferredActionClient {
	return &AarmDeferredActionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `aarmdeferredaction.Hooks(f(g(h())))`.
func (c *AarmDeferredActionClient) Use(hooks ...Hook) {
	c.hooks.AarmDeferredAction = append(c.hooks.AarmDeferredAction, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `aarmdeferredaction.Intercept(f(g(h())))`.
func (c *AarmDeferredActionClient) Intercept(interceptors ...Interceptor) {
	c.inters.AarmDeferredAction = append(c.inters.AarmDeferredAction, interceptors...)
}

// Create returns a builder for creating a AarmDeferredAction entity.
func (c *AarmDeferredActionClient) Create() *AarmDeferredActionCreate {
	mutation := newAarmDeferredActionMutation(c.config, OpCreate)
	return &AarmDeferredActionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AarmDeferredAction entities.
func (c *AarmDeferredActionClient) CreateBulk(builders ...*AarmDeferredActionCreate) *AarmDeferredActionCreateBulk {
	return &AarmDeferredActionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AarmDeferredActionClient) MapCreateBulk(slice any, setFunc func(*AarmDeferredActionCreate, int)) *AarmDeferredActionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AarmDeferredActionCreateBulk{err: fmt.Errorf("calling to AarmDeferredActionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AarmDeferredActionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AarmDeferredActionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AarmDeferredAction.
func (c *AarmDeferredActionClient) Update() *AarmDeferredActionUpdate {
	mutation := newAarmDeferredActionMutation(c.config, OpUpdate)
	return &AarmDeferredActionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AarmDeferredActionClient) UpdateOne(_m *AarmDeferredAction) *AarmDeferredActionUpdateOne {
	mutation := newAarmDeferredActionMutation(c.config, OpUpdateOne, withAarmDeferredAction(_m))
	return &AarmDeferredActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AarmDeferredActionClient) UpdateOneID(id uuid.UUID) *AarmDeferredActionUpdateOne {
	mutation := newAarmDeferredActionMutation(c.config, OpUpdateOne, withAarmDeferredActionID(id))
	return &AarmDeferredActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AarmDeferredAction.
func (c *AarmDeferredActionClient) Delete() *AarmDeferredActionDelete {
	mutation := newAarmDeferredActionMutation(c.config, OpDelete)
	return &AarmDeferredActionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AarmDeferredActionClient) DeleteOne(_m *AarmDeferredAction) *AarmDeferredActionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AarmDeferredActionClient) DeleteOneID(id uuid.UUID) *AarmDeferredActionDeleteOne {
	builder := c.Delete().Where(aarmdeferredaction.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AarmDeferredActionDeleteOne{builder}
}

// Query returns a query builder for AarmDeferredAction.
func (c *AarmDeferredActionClient) Query() *AarmDeferredActionQuery {
	return &AarmDeferredActionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAarmDeferredAction},
		inters: c.Interceptors(),
	}
}

// Get returns a AarmDeferredAction entity by its id.
func (c *AarmDeferredActionClient) Get(ctx context.Context, id uuid.UUID) (*AarmDeferredAction, error) {
	return c.Query().Where(aarmdeferredaction.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AarmDeferredActionClient) GetX(ctx context.Context, id uuid.UUID) *AarmDeferredAction {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AarmDeferredActionClient) Hooks() []Hook {
	return c.hooks.AarmDeferredAction
}

// Interceptors returns the client interceptors.
func (c *AarmDeferredActionClient) Interceptors() []Interceptor {
	return c.inters.AarmDeferredAction
}

func (c *AarmDeferredActionClient) mutate(ctx context.Context, m *AarmDeferredActionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AarmDeferredActionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AarmDeferredActionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AarmDeferredActionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AarmDeferredActionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AarmDeferredAction mutation op: %q", m.Op())
	}
}

// AarmReceiptClient is a client for the AarmReceipt schema.
type AarmReceiptClient struct {
	config
}

// NewAarmReceiptClient returns a client for the AarmReceipt from the given config.
func NewAarmReceiptClient(c config) *AarmReceiptClient {
	return &AarmReceiptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `aarmreceipt.Hooks(f(g(h())))`.
func (c *AarmReceiptClient) Use(hooks ...Hook) {
	c.hooks.AarmReceipt = append(c.hooks.AarmReceipt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `aarmreceipt.Intercept(f(g(h())))`.
func (c *AarmReceiptClient) Intercept(interceptors ...Interceptor) {
	c.inters.AarmReceipt = append(c.inters.AarmReceipt, interceptors...)
}

// Create returns a builder for creating a AarmReceipt entity.
func (c *AarmReceiptClient) Create() *AarmReceiptCreate {
	mutation := newAarmReceiptMutation(c.config, OpCreate)
	return &AarmReceiptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AarmReceipt entities.
func (c *AarmReceiptClient) CreateBulk(builders ...*AarmReceiptCreate) *AarmReceiptCreateBulk {
	return &AarmReceiptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AarmReceiptClient) MapCreateBulk(slice any, setFunc func(*AarmReceiptCreate, int)) *AarmReceiptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AarmReceiptCreateBulk{err: fmt.Errorf("calling to AarmReceiptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AarmReceiptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AarmReceiptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AarmReceipt.
func (c *AarmReceiptClient) Update() *AarmReceiptUpdate {
	mutation := newAarmReceiptMutation(c.config, OpUpdate)
	return &AarmReceiptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AarmReceiptClient) UpdateOne(_m *AarmReceipt) *AarmReceiptUpdateOne {
	mutation := newAarmReceiptMutation(c.config, OpUpdateOne, withAarmReceipt(_m))
	return &AarmReceiptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AarmReceiptClient) UpdateOneID(id uuid.UUID) *AarmReceiptUpdateOne {
	mutation := newAarmReceiptMutation(c.config, OpUpdateOne, withAarmReceiptID(id))
	return &AarmReceiptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AarmReceipt.
func (c *AarmReceiptClient) Delete() *AarmReceiptDelete {
	mutation := newAarmReceiptMutation(c.config, OpDelete)
	return &AarmReceiptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AarmReceiptClient) DeleteOne(_m *AarmReceipt) *AarmReceiptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AarmReceiptClient) DeleteOneID(id uuid.UUID) *AarmReceiptDeleteOne {
	builder := c.Delete().Where(aarmreceipt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AarmReceiptDeleteOne{builder}
}

// Query returns a query builder for AarmReceipt.
func (c *AarmReceiptClient) Query() *AarmReceiptQuery {
	return &AarmReceiptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAarmReceipt},
		inters: c.Interceptors(),
	}
}

// Get returns a AarmReceipt entity by its id.
func (c *AarmReceiptClient) Get(ctx context.Context, id uuid.UUID) (*AarmReceipt, error) {
	return c.Query().Where(aarmreceipt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AarmReceiptClient) GetX(ctx context.Context, id uuid.UUID) *AarmReceipt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AarmReceiptClient) Hooks() []Hook {
	return c.hooks.AarmReceipt
}

// Interceptors returns the client interceptors.
func (c *AarmReceiptClient) Interceptors() []Interceptor {
	return c.inters.AarmReceipt
}

func (c *AarmReceiptClient) mutate(ctx context.Context, m *AarmReceiptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AarmReceiptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AarmReceiptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AarmReceiptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AarmReceiptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AarmReceipt mutation op: %q", m.Op())
	}
}

// AuditEventClient is a client for the AuditEvent schema.
type AuditEventClient struct {
	config
}

// NewAuditEventClient returns a client for the AuditEvent from the given config.
func NewAuditEventClient(c config) *AuditEventClient {
	return &AuditEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditevent.Hooks(f(g(h())))`.
func (c *AuditEventClient) Use(hooks ...Hook) {
	c.hooks.AuditEvent = append(c.hooks.AuditEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditevent.Intercept(f(g(h())))`.
func (c *AuditEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditEvent = append(c.inters.AuditEvent, interceptors...)
}

// Create returns a builder for creating a AuditEvent entity.
func (c *AuditEventClient) Create() *AuditEventCreate {
	mutation := newAuditEventMutation(c.config, OpCreate)
	return &AuditEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditEvent entities.
func (c *AuditEventClient) CreateBulk(builders ...*AuditEventCreate) *AuditEventCreateBulk {
	return &AuditEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditEventClient) MapCreateBulk(slice any, setFunc func(*AuditEventCreate, int)) *AuditEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditEventCreateBulk{err: fmt.Errorf("calling to AuditEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditEvent.
func (c *AuditEventClient) Update() *AuditEventUpdate {
	mutation := newAuditEventMutation(c.config, OpUpdate)
	return &AuditEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditEventClient) UpdateOne(_m *AuditEvent) *AuditEventUpdateOne {
	mutation := newAuditEventMutation(c.config, OpUpdateOne, withAuditEvent(_m))
	return &AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditEventClient) UpdateOneID(id uuid.UUID) *AuditEventUpdateOne {
	mutation := newAuditEventMutation(c.config, OpUpdateOne, withAuditEventID(id))
	return &AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditEvent.
func (c *AuditEventClient) Delete() *AuditEventDelete {
	mutation := newAuditEventMutation(c.config, OpDelete)
	return &AuditEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditEventClient) DeleteOne(_m *AuditEvent) *AuditEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditEventClient) DeleteOneID(id uuid.UUID) *AuditEventDeleteOne {
	builder := c.Delete().Where(auditevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditEventDeleteOne{builder}
}

// Query returns a query builder for AuditEvent.
func (c *AuditEventClient) Query() *AuditEventQuery {
	return &AuditEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditEvent entity by its id.
func (c *AuditEventClient) Get(ctx context.Context, id uuid.UUID) (*AuditEvent, error) {
	return c.Query().Where(auditevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditEventClient) GetX(ctx context.Context, id uuid.UUID) *AuditEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a AuditEvent.
func (c *AuditEventClient) QuerySession(_m *AuditEvent) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(auditevent.Table, auditevent.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, auditevent.SessionTable, auditevent.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AuditEventClient) Hooks() []Hook {
	return c.hooks.AuditEvent
}

// Interceptors returns the client interceptors.
func (c *AuditEventClient) Interceptors() []Interceptor {
	return c.inters.AuditEvent
}

func (c *AuditEventClient) mutate(ctx context.Context, m *AuditEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditEvent mutation op: %q", m.Op())
	}
}

// AuditStreamCursorClient is a client for the AuditStreamCursor schema.
type AuditStreamCursorClient struct {
	config
}

// NewAuditStreamCursorClient returns a client for the AuditStreamCursor from the given config.
func NewAuditStreamCursorClient(c config) *AuditStreamCursorClient {
	return &AuditStreamCursorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `auditstreamcursor.Hooks(f(g(h())))`.
func (c *AuditStreamCursorClient) Use(hooks ...Hook) {
	c.hooks.AuditStreamCursor = append(c.hooks.AuditStreamCursor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `auditstreamcursor.Intercept(f(g(h())))`.
func (c *AuditStreamCursorClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuditStreamCursor = append(c.inters.AuditStreamCursor, interceptors...)
}

// Create returns a builder for creating a AuditStreamCursor entity.
func (c *AuditStreamCursorClient) Create() *AuditStreamCursorCreate {
	mutation := newAuditStreamCursorMutation(c.config, OpCreate)
	return &AuditStreamCursorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuditStreamCursor entities.
func (c *AuditStreamCursorClient) CreateBulk(builders ...*AuditStreamCursorCreate) *AuditStreamCursorCreateBulk {
	return &AuditStreamCursorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuditStreamCursorClient) MapCreateBulk(slice any, setFunc func(*AuditStreamCursorCreate, int)) *AuditStreamCursorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuditStreamCursorCreateBulk{err: fmt.Errorf("calling to AuditStreamCursorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuditStreamCursorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuditStreamCursorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuditStreamCursor.
func (c *AuditStreamCursorClient) Update() *AuditStreamCursorUpdate {
	mutation := newAuditStreamCursorMutation(c.config, OpUpdate)
	return &AuditStreamCursorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuditStreamCursorClient) UpdateOne(_m *AuditStreamCursor) *AuditStreamCursorUpdateOne {
	mutation := newAuditStreamCursorMutation(c.config, OpUpdateOne, withAuditStreamCursor(_m))
	return &AuditStreamCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuditStreamCursorClient) UpdateOneID(id string) *AuditStreamCursorUpdateOne {
	mutation := newAuditStreamCursorMutation(c.config, OpUpdateOne, withAuditStreamCursorID(id))
	return &AuditStreamCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuditStreamCursor.
func (c *AuditStreamCursorClient) Delete() *AuditStreamCursorDelete {
	mutation := newAuditStreamCursorMutation(c.config, OpDelete)
	return &AuditStreamCursorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuditStreamCursorClient) DeleteOne(_m *AuditStreamCursor) *AuditStreamCursorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuditStreamCursorClient) DeleteOneID(id string) *AuditStreamCursorDeleteOne {
	builder := c.Delete().Where(auditstreamcursor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuditStreamCursorDeleteOne{builder}
}

// Query returns a query builder for AuditStreamCursor.
func (c *AuditStreamCursorClient) Query() *AuditStreamCursorQuery {
	return &AuditStreamCursorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuditStreamCursor},
		inters: c.Interceptors(),
	}
}

// Get returns a AuditStreamCursor entity by its id.
func (c *AuditStreamCursorClient) Get(ctx context.Context, id string) (*AuditStreamCursor, error) {
	return c.Query().Where(auditstreamcursor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuditStreamCursorClient) GetX(ctx context.Context, id string) *AuditStreamCursor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AuditStreamCursorClient) Hooks() []Hook {
	return c.hooks.AuditStreamCursor
}

// Interceptors returns the client interceptors.
func (c *AuditStreamCursorClient) Interceptors() []Interceptor {
	return c.inters.AuditStreamCursor
}

func (c *AuditStreamCursorClient) mutate(ctx context.Context, m *AuditStreamCursorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuditStreamCursorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuditStreamCursorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuditStreamCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuditStreamCursorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuditStreamCursor mutation op: %q", m.Op())
	}
}

// ContextEntryClient is a client for the ContextEntry schema.
type ContextEntryClient struct {
	config
}

// NewContextEntryClient returns a client for the ContextEntry from the given config.
func NewContextEntryClient(c config) *ContextEntryClient {
	return &ContextEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `contextentry.Hooks(f(g(h())))`.
func (c *ContextEntryClient) Use(hooks ...Hook) {
	c.hooks.ContextEntry = append(c.hooks.ContextEntry, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `contextentry.Intercept(f(g(h())))`.
func (c *ContextEntryClient) Intercept(interceptors ...Interceptor) {
	c.inters.ContextEntry = append(c.inters.ContextEntry, interceptors...)
}

// Create returns a builder for creating a ContextEntry entity.
func (c *ContextEntryClient) Create() *ContextEntryCreate {
	mutation := newContextEntryMutation(c.config, OpCreate)
	return &ContextEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ContextEntry entities.
func (c *ContextEntryClient) CreateBulk(builders ...*ContextEntryCreate) *ContextEntryCreateBulk {
	return &ContextEntryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ContextEntryClient) MapCreateBulk(slice any, setFunc func(*ContextEntryCreate, int)) *ContextEntryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ContextEntryCreateBulk{err: fmt.Errorf("calling to ContextEntryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ContextEntryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ContextEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ContextEntry.
func (c *ContextEntryClient) Update() *ContextEntryUpdate {
	mutation := newContextEntryMutation(c.config, OpUpdate)
	return &ContextEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ContextEntryClient) UpdateOne(_m *ContextEntry) *ContextEntryUpdateOne {
	mutation := newContextEntryMutation(c.config, OpUpdateOne, withContextEntry(_m))
	return &ContextEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ContextEntryClient) UpdateOneID(id uuid.UUID) *ContextEntryUpdateOne {
	mutation := newContextEntryMutation(c.config, OpUpdateOne, withContextEntryID(id))
	return &ContextEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ContextEntry.
func (c *ContextEntryClient) Delete() *ContextEntryDelete {
	mutation := newContextEntryMutation(c.config, OpDelete)
	return &ContextEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ContextEntryClient) DeleteOne(_m *ContextEntry) *ContextEntryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ContextEntryClient) DeleteOneID(id uuid.UUID) *ContextEntryDeleteOne {
	builder := c.Delete().Where(contextentry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ContextEntryDeleteOne{builder}
}

// Query returns a query builder for ContextEntry.
func (c *ContextEntryClient) Query() *ContextEntryQuery {
	return &ContextEntryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeContextEntry},
		inters: c.Interceptors(),
	}
}

// Get returns a ContextEntry entity by its id.
func (c *ContextEntryClient) Get(ctx context.Context, id uuid.UUID) (*ContextEntry, error) {
	return c.Query().Where(contextentry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ContextEntryClient) GetX(ctx context.Context, id uuid.UUID) *ContextEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ContextEntryClient) Hooks() []Hook {
	return c.hooks.ContextEntry
}

// Interceptors returns the client interceptors.
func (c *ContextEntryClient) Interceptors() []Interceptor {
	return c.inters.ContextEntry
}

func (c *ContextEntryClient) mutate(ctx context.Context, m *ContextEntryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ContextEntryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ContextEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ContextEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ContextEntryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ContextEntry mutation op: %q", m.Op())
	}
}

// ContextStateClient is a client for the ContextState schema.
type ContextStateClient struct {
	config
}

// NewContextStateClient returns a client for the ContextState from the given config.
func NewContextStateClient(c config) *ContextStateClient {
	return &ContextStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `contextstate.Hooks(f(g(h())))`.
func (c *ContextStateClient) Use(hooks ...Hook) {
	c.hooks.ContextState = append(c.hooks.ContextState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `contextstate.Intercept(f(g(h())))`.
func (c *ContextStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.ContextState = append(c.inters.ContextState, interceptors...)
}

// Create returns a builder for creating a ContextState entity.
func (c *ContextStateClient) Create() *ContextStateCreate {
	mutation := newContextStateMutation(c.config, OpCreate)
	return &ContextStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ContextState entities.
func (c *ContextStateClient) CreateBulk(builders ...*ContextStateCreate) *ContextStateCreateBulk {
	return &ContextStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ContextStateClient) MapCreateBulk(slice any, setFunc func(*ContextStateCreate, int)) *ContextStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ContextStateCreateBulk{err: fmt.Errorf("calling to ContextStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ContextStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ContextStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ContextState.
func (c *ContextStateClient) Update() *ContextStateUpdate {
	mutation := newContextStateMutation(c.config, OpUpdate)
	return &ContextStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ContextStateClient) UpdateOne(_m *ContextState) *ContextStateUpdateOne {
	mutation := newContextStateMutation(c.config, OpUpdateOne, withContextState(_m))
	return &ContextStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ContextStateClient) UpdateOneID(id int) *ContextStateUpdateOne {
	mutation := newContextStateMutation(c.config, OpUpdateOne, withContextStateID(id))
	return &ContextStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ContextState.
func (c *ContextStateClient) Delete() *ContextStateDelete {
	mutation := newContextStateMutation(c.config, OpDelete)
	return &ContextStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ContextStateClient) DeleteOne(_m *ContextState) *ContextStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ContextStateClient) DeleteOneID(id int) *ContextStateDeleteOne {
	builder := c.Delete().Where(contextstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ContextStateDeleteOne{builder}
}

// Query returns a query builder for ContextState.
func (c *ContextStateClient) Query() *ContextStateQuery {
	return &ContextStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeContextState},
		inters: c.Interceptors(),
	}
}

// Get returns a ContextState entity by its id.
func (c *ContextStateClient) Get(ctx context.Context, id int) (*ContextState, error) {
	return c.Query().Where(contextstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ContextStateClient) GetX(ctx context.Context, id int) *ContextState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ContextStateClient) Hooks() []Hook {
	return c.hooks.ContextState
}

// Interceptors returns the client interceptors.
func (c *ContextStateClient) Interceptors() []Interceptor {
	return c.inters.ContextState
}

func (c *ContextStateClient) mutate(ctx context.Context, m *ContextStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ContextStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ContextStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ContextStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ContextStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ContextState mutation op: %q", m.Op())
	}
}

// EventStreamCursorClient is a client for the EventStreamCursor schema.
type EventStreamCursorClient struct {
	config
}

// NewEventStreamCursorClient returns a client for the EventStreamCursor from the given config.
func NewEventStreamCursorClient(c config) *EventStreamCursorClient {
	return &EventStreamCursorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `eventstreamcursor.Hooks(f(g(h())))`.
func (c *EventStreamCursorClient) Use(hooks ...Hook) {
	c.hooks.EventStreamCursor = append(c.hooks.EventStreamCursor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `eventstreamcursor.Intercept(f(g(h())))`.
func (c *EventStreamCursorClient) Intercept(interceptors ...Interceptor) {
	c.inters.EventStreamCursor = append(c.inters.EventStreamCursor, interceptors...)
}

// Create returns a builder for creating a EventStreamCursor entity.
func (c *EventStreamCursorClient) Create() *EventStreamCursorCreate {
	mutation := newEventStreamCursorMutation(c.config, OpCreate)
	return &EventStreamCursorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EventStreamCursor entities.
func (c *EventStreamCursorClient) CreateBulk(builders ...*EventStreamCursorCreate) *EventStreamCursorCreateBulk {
	return &EventStreamCursorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EventStreamCursorClient) MapCreateBulk(slice any, setFunc func(*EventStreamCursorCreate, int)) *EventStreamCursorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EventStreamCursorCreateBulk{err: fmt.Errorf("calling to EventStreamCursorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EventStreamCursorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EventStreamCursorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EventStreamCursor.
func (c *EventStreamCursorClient) Update() *EventStreamCursorUpdate {
	mutation := newEventStreamCursorMutation(c.config, OpUpdate)
	return &EventStreamCursorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EventStreamCursorClient) UpdateOne(_m *EventStreamCursor) *EventStreamCursorUpdateOne {
	mutation := newEventStreamCursorMutation(c.config, OpUpdateOne, withEventStreamCursor(_m))
	return &EventStreamCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EventStreamCursorClient) UpdateOneID(id string) *EventStreamCursorUpdateOne {
	mutation := newEventStreamCursorMutation(c.config, OpUpdateOne, withEventStreamCursorID(id))
	return &EventStreamCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EventStreamCursor.
func (c *EventStreamCursorClient) Delete() *EventStreamCursorDelete {
	mutation := newEventStreamCursorMutation(c.config, OpDelete)
	return &EventStreamCursorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EventStreamCursorClient) DeleteOne(_m *EventStreamCursor) *EventStreamCursorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EventStreamCursorClient) DeleteOneID(id string) *EventStreamCursorDeleteOne {
	builder := c.Delete().Where(eventstreamcursor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EventStreamCursorDeleteOne{builder}
}

// Query returns a query builder for EventStreamCursor.
func (c *EventStreamCursorClient) Query() *EventStreamCursorQuery {
	return &EventStreamCursorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEventStreamCursor},
		inters: c.Interceptors(),
	}
}

// Get returns a EventStreamCursor entity by its id.
func (c *EventStreamCursorClient) Get(ctx context.Context, id string) (*EventStreamCursor, error) {
	return c.Query().Where(eventstreamcursor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EventStreamCursorClient) GetX(ctx context.Context, id string) *EventStreamCursor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EventStreamCursorClient) Hooks() []Hook {
	return c.hooks.EventStreamCursor
}

// Interceptors returns the client interceptors.
func (c *EventStreamCursorClient) Interceptors() []Interceptor {
	return c.inters.EventStreamCursor
}

func (c *EventStreamCursorClient) mutate(ctx context.Context, m *EventStreamCursorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EventStreamCursorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EventStreamCursorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EventStreamCursorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EventStreamCursorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EventStreamCursor mutation op: %q", m.Op())
	}
}

// SelfAuditClient is a client for the SelfAudit schema.
type SelfAuditClient struct {
	config
}

// NewSelfAuditClient returns a client for the SelfAudit from the given config.
func NewSelfAuditClient(c config) *SelfAuditClient {
	return &SelfAuditClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `selfaudit.Hooks(f(g(h())))`.
func (c *SelfAuditClient) Use(hooks ...Hook) {
	c.hooks.SelfAudit = append(c.hooks.SelfAudit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `selfaudit.Intercept(f(g(h())))`.
func (c *SelfAuditClient) Intercept(interceptors ...Interceptor) {
	c.inters.SelfAudit = append(c.inters.SelfAudit, interceptors...)
}

// Create returns a builder for creating a SelfAudit entity.
func (c *SelfAuditClient) Create() *SelfAuditCreate {
	mutation := newSelfAuditMutation(c.config, OpCreate)
	return &SelfAuditCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SelfAudit entities.
func (c *SelfAuditClient) CreateBulk(builders ...*SelfAuditCreate) *SelfAuditCreateBulk {
	return &SelfAuditCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SelfAuditClient) MapCreateBulk(slice any, setFunc func(*SelfAuditCreate, int)) *SelfAuditCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SelfAuditCreateBulk{err: fmt.Errorf("calling to SelfAuditClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SelfAuditCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SelfAuditCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SelfAudit.
func (c *SelfAuditClient) Update() *SelfAuditUpdate {
	mutation := newSelfAuditMutation(c.config, OpUpdate)
	return &SelfAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SelfAuditClient) UpdateOne(_m *SelfAudit) *SelfAuditUpdateOne {
	mutation := newSelfAuditMutation(c.config, OpUpdateOne, withSelfAudit(_m))
	return &SelfAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SelfAuditClient) UpdateOneID(id uuid.UUID) *SelfAuditUpdateOne {
	mutation := newSelfAuditMutation(c.config, OpUpdateOne, withSelfAuditID(id))
	return &SelfAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SelfAudit.
func (c *SelfAuditClient) Delete() *SelfAuditDelete {
	mutation := newSelfAuditMutation(c.config, OpDelete)
	return &SelfAuditDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SelfAuditClient) DeleteOne(_m *SelfAudit) *SelfAuditDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SelfAuditClient) DeleteOneID(id uuid.UUID) *SelfAuditDeleteOne {
	builder := c.Delete().Where(selfaudit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SelfAuditDeleteOne{builder}
}

// Query returns a query builder for SelfAudit.
func (c *SelfAuditClient) Query() *SelfAuditQuery {
	return &SelfAuditQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSelfAudit},
		inters: c.Interceptors(),
	}
}

// Get returns a SelfAudit entity by its id.
func (c *SelfAuditClient) Get(ctx context.Context, id uuid.UUID) (*SelfAudit, error) {
	return c.Query().Where(selfaudit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SelfAuditClient) GetX(ctx context.Context, id uuid.UUID) *SelfAudit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SelfAuditClient) Hooks() []Hook {
	return c.hooks.SelfAudit
}

// Interceptors returns the client interceptors.
func (c *SelfAuditClient) Interceptors() []Interceptor {
	return c.inters.SelfAudit
}

func (c *SelfAuditClient) mutate(ctx context.Context, m *SelfAuditMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SelfAuditCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SelfAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SelfAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SelfAuditDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SelfAudit mutation op: %q", m.Op())
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id uuid.UUID) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id uuid.UUID) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id uuid.UUID) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id uuid.UUID) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEvents queries the events edge of a Session.
func (c *SessionClient) QueryEvents(_m *Session) *AuditEventQuery {
	query := (&AuditEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(auditevent.Table, auditevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.EventsTable, session.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Session mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AarmDeferredAction, AarmReceipt, AuditEvent, AuditStreamCursor, ContextEntry,
		ContextState, EventStreamCursor, SelfAudit, Session []ent.Hook
	}
	inters struct {
		AarmDeferredAction, AarmReceipt, AuditEvent, AuditStreamCursor, ContextEntry,
		ContextState, EventStreamCursor, SelfAudit, Session []ent.Interceptor
	}
)
