// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/contextstate"
)

// ContextState is the model entity for the ContextState schema.
type ContextState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID uuid.UUID `json:"session_id,omitempty"`
	// LastEntryAt holds the value of the "last_entry_at" field.
	LastEntryAt time.Time `json:"last_entry_at,omitempty"`
	// ToolsUsed holds the value of the "tools_used" field.
	ToolsUsed []string `json:"tools_used,omitempty"`
	// ClassificationsSeen holds the value of the "classifications_seen" field.
	ClassificationsSeen []string `json:"classifications_seen,omitempty"`
	// TagsSeen holds the value of the "tags_seen" field.
	TagsSeen map[string]int64 `json:"tags_seen,omitempty"`
	// OriginsSeen holds the value of the "origins_seen" field.
	OriginsSeen []string `json:"origins_seen,omitempty"`
	// EntitiesSeen holds the value of the "entities_seen" field.
	EntitiesSeen []string `json:"entities_seen,omitempty"`
	// EgressHosts holds the value of the "egress_hosts" field.
	EgressHosts []string `json:"egress_hosts,omitempty"`
	// LastIntentSeq holds the value of the "last_intent_seq" field.
	LastIntentSeq *int64 `json:"last_intent_seq,omitempty"`
	// LastIntentAt holds the value of the "last_intent_at" field.
	LastIntentAt *time.Time `json:"last_intent_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContextState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contextstate.FieldToolsUsed, contextstate.FieldClassificationsSeen, contextstate.FieldTagsSeen, contextstate.FieldOriginsSeen, contextstate.FieldEntitiesSeen, contextstate.FieldEgressHosts:
			values[i] = new([]byte)
		case contextstate.FieldID, contextstate.FieldLastIntentSeq:
			values[i] = new(sql.NullInt64)
		case contextstate.FieldLastEntryAt, contextstate.FieldLastIntentAt:
			values[i] = new(sql.NullTime)
		case contextstate.FieldSessionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContextState fields.
func (_m *ContextState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contextstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case contextstate.FieldSessionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value != nil {
				_m.SessionID = *value
			}
		case contextstate.FieldLastEntryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_entry_at", values[i])
			} else if value.Valid {
				_m.LastEntryAt = value.Time
			}
		case contextstate.FieldToolsUsed:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tools_used", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ToolsUsed); err != nil {
					return fmt.Errorf("unmarshal field tools_used: %w", err)
				}
			}
		case contextstate.FieldClassificationsSeen:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field classifications_seen", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ClassificationsSeen); err != nil {
					return fmt.Errorf("unmarshal field classifications_seen: %w", err)
				}
			}
		case contextstate.FieldTagsSeen:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags_seen", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TagsSeen); err != nil {
					return fmt.Errorf("unmarshal field tags_seen: %w", err)
				}
			}
		case contextstate.FieldOriginsSeen:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field origins_seen", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OriginsSeen); err != nil {
					return fmt.Errorf("unmarshal field origins_seen: %w", err)
				}
			}
		case contextstate.FieldEntitiesSeen:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field entities_seen", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EntitiesSeen); err != nil {
					return fmt.Errorf("unmarshal field entities_seen: %w", err)
				}
			}
		case contextstate.FieldEgressHosts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field egress_hosts", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EgressHosts); err != nil {
					return fmt.Errorf("unmarshal field egress_hosts: %w", err)
				}
			}
		case contextstate.FieldLastIntentSeq:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_intent_seq", values[i])
			} else if value.Valid {
				_m.LastIntentSeq = new(int64)
				*_m.LastIntentSeq = value.Int64
			}
		case contextstate.FieldLastIntentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_intent_at", values[i])
			} else if value.Valid {
				_m.LastIntentAt = new(time.Time)
				*_m.LastIntentAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContextState.
// This includes values selected through modifiers, order, etc.
func (_m *ContextState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ContextState.
// Note that you need to call ContextState.Unwrap() before calling this method if this ContextState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContextState) Update() *ContextStateUpdateOne {
	return NewContextStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContextState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContextState) Unwrap() *ContextState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContextState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContextState) String() string {
	var builder strings.Builder
	builder.WriteString("ContextState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionID))
	builder.WriteString(", ")
	builder.WriteString("last_entry_at=")
	builder.WriteString(_m.LastEntryAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tools_used=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolsUsed))
	builder.WriteString(", ")
	builder.WriteString("classifications_seen=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClassificationsSeen))
	builder.WriteString(", ")
	builder.WriteString("tags_seen=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagsSeen))
	builder.WriteString(", ")
	builder.WriteString("origins_seen=")
	builder.WriteString(fmt.Sprintf("%v", _m.OriginsSeen))
	builder.WriteString(", ")
	builder.WriteString("entities_seen=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntitiesSeen))
	builder.WriteString(", ")
	builder.WriteString("egress_hosts=")
	builder.WriteString(fmt.Sprintf("%v", _m.EgressHosts))
	builder.WriteString(", ")
	if v := _m.LastIntentSeq; v != nil {
		builder.WriteString("last_intent_seq=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastIntentAt; v != nil {
		builder.WriteString("last_intent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ContextStates is a parsable slice of ContextState.
type ContextStates []*ContextState
