// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/gryph/storage/ent/eventstreamcursor"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// EventStreamCursorUpdate is the builder for updating EventStreamCursor entities.
type EventStreamCursorUpdate struct {
	config
	hooks    []Hook
	mutation *EventStreamCursorMutation
}

// Where appends a list predicates to the EventStreamCursorUpdate builder.
func (_u *EventStreamCursorUpdate) Where(ps ...predicate.EventStreamCursor) *EventStreamCursorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *EventStreamCursorUpdate) SetLastSyncedAt(v time.Time) *EventStreamCursorUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *EventStreamCursorUpdate) SetNillableLastSyncedAt(v *time.Time) *EventStreamCursorUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetLastID sets the "last_id" field.
func (_u *EventStreamCursorUpdate) SetLastID(v string) *EventStreamCursorUpdate {
	_u.mutation.SetLastID(v)
	return _u
}

// SetNillableLastID sets the "last_id" field if the given value is not nil.
func (_u *EventStreamCursorUpdate) SetNillableLastID(v *string) *EventStreamCursorUpdate {
	if v != nil {
		_u.SetLastID(*v)
	}
	return _u
}

// ClearLastID clears the value of the "last_id" field.
func (_u *EventStreamCursorUpdate) ClearLastID() *EventStreamCursorUpdate {
	_u.mutation.ClearLastID()
	return _u
}

// Mutation returns the EventStreamCursorMutation object of the builder.
func (_u *EventStreamCursorUpdate) Mutation() *EventStreamCursorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventStreamCursorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventStreamCursorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventStreamCursorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventStreamCursorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EventStreamCursorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(eventstreamcursor.Table, eventstreamcursor.Columns, sqlgraph.NewFieldSpec(eventstreamcursor.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(eventstreamcursor.FieldLastSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastID(); ok {
		_spec.SetField(eventstreamcursor.FieldLastID, field.TypeString, value)
	}
	if _u.mutation.LastIDCleared() {
		_spec.ClearField(eventstreamcursor.FieldLastID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventstreamcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventStreamCursorUpdateOne is the builder for updating a single EventStreamCursor entity.
type EventStreamCursorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventStreamCursorMutation
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *EventStreamCursorUpdateOne) SetLastSyncedAt(v time.Time) *EventStreamCursorUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *EventStreamCursorUpdateOne) SetNillableLastSyncedAt(v *time.Time) *EventStreamCursorUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetLastID sets the "last_id" field.
func (_u *EventStreamCursorUpdateOne) SetLastID(v string) *EventStreamCursorUpdateOne {
	_u.mutation.SetLastID(v)
	return _u
}

// SetNillableLastID sets the "last_id" field if the given value is not nil.
func (_u *EventStreamCursorUpdateOne) SetNillableLastID(v *string) *EventStreamCursorUpdateOne {
	if v != nil {
		_u.SetLastID(*v)
	}
	return _u
}

// ClearLastID clears the value of the "last_id" field.
func (_u *EventStreamCursorUpdateOne) ClearLastID() *EventStreamCursorUpdateOne {
	_u.mutation.ClearLastID()
	return _u
}

// Mutation returns the EventStreamCursorMutation object of the builder.
func (_u *EventStreamCursorUpdateOne) Mutation() *EventStreamCursorMutation {
	return _u.mutation
}

// Where appends a list predicates to the EventStreamCursorUpdate builder.
func (_u *EventStreamCursorUpdateOne) Where(ps ...predicate.EventStreamCursor) *EventStreamCursorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventStreamCursorUpdateOne) Select(field string, fields ...string) *EventStreamCursorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EventStreamCursor entity.
func (_u *EventStreamCursorUpdateOne) Save(ctx context.Context) (*EventStreamCursor, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventStreamCursorUpdateOne) SaveX(ctx context.Context) *EventStreamCursor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventStreamCursorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventStreamCursorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EventStreamCursorUpdateOne) sqlSave(ctx context.Context) (_node *EventStreamCursor, err error) {
	_spec := sqlgraph.NewUpdateSpec(eventstreamcursor.Table, eventstreamcursor.Columns, sqlgraph.NewFieldSpec(eventstreamcursor.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventStreamCursor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventstreamcursor.FieldID)
		for _, f := range fields {
			if !eventstreamcursor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventstreamcursor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(eventstreamcursor.FieldLastSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastID(); ok {
		_spec.SetField(eventstreamcursor.FieldLastID, field.TypeString, value)
	}
	if _u.mutation.LastIDCleared() {
		_spec.ClearField(eventstreamcursor.FieldLastID, field.TypeString)
	}
	_node = &EventStreamCursor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventstreamcursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
