// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/gryph/storage/ent/eventstreamcursor"
	"github.com/safedep/gryph/storage/ent/predicate"
)

// EventStreamCursorDelete is the builder for deleting a EventStreamCursor entity.
type EventStreamCursorDelete struct {
	config
	hooks    []Hook
	mutation *EventStreamCursorMutation
}

// Where appends a list predicates to the EventStreamCursorDelete builder.
func (_d *EventStreamCursorDelete) Where(ps ...predicate.EventStreamCursor) *EventStreamCursorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EventStreamCursorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EventStreamCursorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EventStreamCursorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eventstreamcursor.Table, sqlgraph.NewFieldSpec(eventstreamcursor.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EventStreamCursorDeleteOne is the builder for deleting a single EventStreamCursor entity.
type EventStreamCursorDeleteOne struct {
	_d *EventStreamCursorDelete
}

// Where appends a list predicates to the EventStreamCursorDelete builder.
func (_d *EventStreamCursorDeleteOne) Where(ps ...predicate.EventStreamCursor) *EventStreamCursorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EventStreamCursorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventstreamcursor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EventStreamCursorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
