// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/auditevent"
	"github.com/safedep/gryph/storage/ent/auditstreamcursor"
	"github.com/safedep/gryph/storage/ent/eventstreamcursor"
	"github.com/safedep/gryph/storage/ent/schema"
	"github.com/safedep/gryph/storage/ent/selfaudit"
	"github.com/safedep/gryph/storage/ent/session"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescSequence is the schema descriptor for sequence field.
	auditeventDescSequence := auditeventFields[2].Descriptor()
	// auditevent.SequenceValidator is a validator for the "sequence" field. It is called by the builders before save.
	auditevent.SequenceValidator = auditeventDescSequence.Validators[0].(func(int) error)
	// auditeventDescTimestamp is the schema descriptor for timestamp field.
	auditeventDescTimestamp := auditeventFields[3].Descriptor()
	// auditevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	auditevent.DefaultTimestamp = auditeventDescTimestamp.Default.(func() time.Time)
	// auditeventDescAgentName is the schema descriptor for agent_name field.
	auditeventDescAgentName := auditeventFields[5].Descriptor()
	// auditevent.AgentNameValidator is a validator for the "agent_name" field. It is called by the builders before save.
	auditevent.AgentNameValidator = auditeventDescAgentName.Validators[0].(func(string) error)
	// auditeventDescIsSensitive is the schema descriptor for is_sensitive field.
	auditeventDescIsSensitive := auditeventFields[16].Descriptor()
	// auditevent.DefaultIsSensitive holds the default value on creation for the is_sensitive field.
	auditevent.DefaultIsSensitive = auditeventDescIsSensitive.Default.(bool)
	// auditeventDescID is the schema descriptor for id field.
	auditeventDescID := auditeventFields[0].Descriptor()
	// auditevent.DefaultID holds the default value on creation for the id field.
	auditevent.DefaultID = auditeventDescID.Default.(func() uuid.UUID)
	auditstreamcursorFields := schema.AuditStreamCursor{}.Fields()
	_ = auditstreamcursorFields
	// auditstreamcursorDescLastSyncedAt is the schema descriptor for last_synced_at field.
	auditstreamcursorDescLastSyncedAt := auditstreamcursorFields[1].Descriptor()
	// auditstreamcursor.DefaultLastSyncedAt holds the default value on creation for the last_synced_at field.
	auditstreamcursor.DefaultLastSyncedAt = auditstreamcursorDescLastSyncedAt.Default.(func() time.Time)
	eventstreamcursorFields := schema.EventStreamCursor{}.Fields()
	_ = eventstreamcursorFields
	// eventstreamcursorDescLastSyncedAt is the schema descriptor for last_synced_at field.
	eventstreamcursorDescLastSyncedAt := eventstreamcursorFields[1].Descriptor()
	// eventstreamcursor.DefaultLastSyncedAt holds the default value on creation for the last_synced_at field.
	eventstreamcursor.DefaultLastSyncedAt = eventstreamcursorDescLastSyncedAt.Default.(func() time.Time)
	selfauditFields := schema.SelfAudit{}.Fields()
	_ = selfauditFields
	// selfauditDescTimestamp is the schema descriptor for timestamp field.
	selfauditDescTimestamp := selfauditFields[1].Descriptor()
	// selfaudit.DefaultTimestamp holds the default value on creation for the timestamp field.
	selfaudit.DefaultTimestamp = selfauditDescTimestamp.Default.(func() time.Time)
	// selfauditDescToolVersion is the schema descriptor for tool_version field.
	selfauditDescToolVersion := selfauditFields[7].Descriptor()
	// selfaudit.ToolVersionValidator is a validator for the "tool_version" field. It is called by the builders before save.
	selfaudit.ToolVersionValidator = selfauditDescToolVersion.Validators[0].(func(string) error)
	// selfauditDescID is the schema descriptor for id field.
	selfauditDescID := selfauditFields[0].Descriptor()
	// selfaudit.DefaultID holds the default value on creation for the id field.
	selfaudit.DefaultID = selfauditDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescAgentName is the schema descriptor for agent_name field.
	sessionDescAgentName := sessionFields[2].Descriptor()
	// session.AgentNameValidator is a validator for the "agent_name" field. It is called by the builders before save.
	session.AgentNameValidator = sessionDescAgentName.Validators[0].(func(string) error)
	// sessionDescStartedAt is the schema descriptor for started_at field.
	sessionDescStartedAt := sessionFields[4].Descriptor()
	// session.DefaultStartedAt holds the default value on creation for the started_at field.
	session.DefaultStartedAt = sessionDescStartedAt.Default.(func() time.Time)
	// sessionDescTotalActions is the schema descriptor for total_actions field.
	sessionDescTotalActions := sessionFields[8].Descriptor()
	// session.DefaultTotalActions holds the default value on creation for the total_actions field.
	session.DefaultTotalActions = sessionDescTotalActions.Default.(int)
	// sessionDescFilesRead is the schema descriptor for files_read field.
	sessionDescFilesRead := sessionFields[9].Descriptor()
	// session.DefaultFilesRead holds the default value on creation for the files_read field.
	session.DefaultFilesRead = sessionDescFilesRead.Default.(int)
	// sessionDescFilesWritten is the schema descriptor for files_written field.
	sessionDescFilesWritten := sessionFields[10].Descriptor()
	// session.DefaultFilesWritten holds the default value on creation for the files_written field.
	session.DefaultFilesWritten = sessionDescFilesWritten.Default.(int)
	// sessionDescCommandsExecuted is the schema descriptor for commands_executed field.
	sessionDescCommandsExecuted := sessionFields[11].Descriptor()
	// session.DefaultCommandsExecuted holds the default value on creation for the commands_executed field.
	session.DefaultCommandsExecuted = sessionDescCommandsExecuted.Default.(int)
	// sessionDescErrors is the schema descriptor for errors field.
	sessionDescErrors := sessionFields[12].Descriptor()
	// session.DefaultErrors holds the default value on creation for the errors field.
	session.DefaultErrors = sessionDescErrors.Default.(int)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
}
