// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/selfaudit"
)

// SelfAuditCreate is the builder for creating a SelfAudit entity.
type SelfAuditCreate struct {
	config
	mutation *SelfAuditMutation
	hooks    []Hook
}

// SetTimestamp sets the "timestamp" field.
func (_c *SelfAuditCreate) SetTimestamp(v time.Time) *SelfAuditCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *SelfAuditCreate) SetNillableTimestamp(v *time.Time) *SelfAuditCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *SelfAuditCreate) SetAction(v selfaudit.Action) *SelfAuditCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetAgentName sets the "agent_name" field.
func (_c *SelfAuditCreate) SetAgentName(v string) *SelfAuditCreate {
	_c.mutation.SetAgentName(v)
	return _c
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_c *SelfAuditCreate) SetNillableAgentName(v *string) *SelfAuditCreate {
	if v != nil {
		_c.SetAgentName(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *SelfAuditCreate) SetDetails(v map[string]interface{}) *SelfAuditCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetResult sets the "result" field.
func (_c *SelfAuditCreate) SetResult(v selfaudit.Result) *SelfAuditCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *SelfAuditCreate) SetNillableResult(v *selfaudit.Result) *SelfAuditCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *SelfAuditCreate) SetErrorMessage(v string) *SelfAuditCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *SelfAuditCreate) SetNillableErrorMessage(v *string) *SelfAuditCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetToolVersion sets the "tool_version" field.
func (_c *SelfAuditCreate) SetToolVersion(v string) *SelfAuditCreate {
	_c.mutation.SetToolVersion(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SelfAuditCreate) SetID(v uuid.UUID) *SelfAuditCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SelfAuditCreate) SetNillableID(v *uuid.UUID) *SelfAuditCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SelfAuditMutation object of the builder.
func (_c *SelfAuditCreate) Mutation() *SelfAuditMutation {
	return _c.mutation
}

// Save creates the SelfAudit in the database.
func (_c *SelfAuditCreate) Save(ctx context.Context) (*SelfAudit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SelfAuditCreate) SaveX(ctx context.Context) *SelfAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SelfAuditCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SelfAuditCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SelfAuditCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := selfaudit.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.Result(); !ok {
		v := selfaudit.DefaultResult
		_c.mutation.SetResult(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := selfaudit.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SelfAuditCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "SelfAudit.timestamp"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SelfAudit.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := selfaudit.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SelfAudit.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "SelfAudit.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := selfaudit.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "SelfAudit.result": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToolVersion(); !ok {
		return &ValidationError{Name: "tool_version", err: errors.New(`ent: missing required field "SelfAudit.tool_version"`)}
	}
	if v, ok := _c.mutation.ToolVersion(); ok {
		if err := selfaudit.ToolVersionValidator(v); err != nil {
			return &ValidationError{Name: "tool_version", err: fmt.Errorf(`ent: validator failed for field "SelfAudit.tool_version": %w`, err)}
		}
	}
	return nil
}

func (_c *SelfAuditCreate) sqlSave(ctx context.Context) (*SelfAudit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SelfAuditCreate) createSpec() (*SelfAudit, *sqlgraph.CreateSpec) {
	var (
		_node = &SelfAudit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(selfaudit.Table, sqlgraph.NewFieldSpec(selfaudit.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(selfaudit.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(selfaudit.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.AgentName(); ok {
		_spec.SetField(selfaudit.FieldAgentName, field.TypeString, value)
		_node.AgentName = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(selfaudit.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(selfaudit.FieldResult, field.TypeEnum, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(selfaudit.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.ToolVersion(); ok {
		_spec.SetField(selfaudit.FieldToolVersion, field.TypeString, value)
		_node.ToolVersion = value
	}
	return _node, _spec
}

// SelfAuditCreateBulk is the builder for creating many SelfAudit entities in bulk.
type SelfAuditCreateBulk struct {
	config
	err      error
	builders []*SelfAuditCreate
}

// Save creates the SelfAudit entities in the database.
func (_c *SelfAuditCreateBulk) Save(ctx context.Context) ([]*SelfAudit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SelfAudit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SelfAuditMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SelfAuditCreateBulk) SaveX(ctx context.Context) []*SelfAudit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SelfAuditCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SelfAuditCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
