// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/safedep/gryph/storage/ent/auditevent"
	"github.com/safedep/gryph/storage/ent/predicate"
	"github.com/safedep/gryph/storage/ent/session"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAgentSessionID sets the "agent_session_id" field.
func (_u *SessionUpdate) SetAgentSessionID(v string) *SessionUpdate {
	_u.mutation.SetAgentSessionID(v)
	return _u
}

// SetNillableAgentSessionID sets the "agent_session_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableAgentSessionID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetAgentSessionID(*v)
	}
	return _u
}

// ClearAgentSessionID clears the value of the "agent_session_id" field.
func (_u *SessionUpdate) ClearAgentSessionID() *SessionUpdate {
	_u.mutation.ClearAgentSessionID()
	return _u
}

// SetAgentName sets the "agent_name" field.
func (_u *SessionUpdate) SetAgentName(v string) *SessionUpdate {
	_u.mutation.SetAgentName(v)
	return _u
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableAgentName(v *string) *SessionUpdate {
	if v != nil {
		_u.SetAgentName(*v)
	}
	return _u
}

// SetAgentVersion sets the "agent_version" field.
func (_u *SessionUpdate) SetAgentVersion(v string) *SessionUpdate {
	_u.mutation.SetAgentVersion(v)
	return _u
}

// SetNillableAgentVersion sets the "agent_version" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableAgentVersion(v *string) *SessionUpdate {
	if v != nil {
		_u.SetAgentVersion(*v)
	}
	return _u
}

// ClearAgentVersion clears the value of the "agent_version" field.
func (_u *SessionUpdate) ClearAgentVersion() *SessionUpdate {
	_u.mutation.ClearAgentVersion()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdate) SetEndedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEndedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdate) ClearEndedAt() *SessionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetWorkingDirectory sets the "working_directory" field.
func (_u *SessionUpdate) SetWorkingDirectory(v string) *SessionUpdate {
	_u.mutation.SetWorkingDirectory(v)
	return _u
}

// SetNillableWorkingDirectory sets the "working_directory" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableWorkingDirectory(v *string) *SessionUpdate {
	if v != nil {
		_u.SetWorkingDirectory(*v)
	}
	return _u
}

// ClearWorkingDirectory clears the value of the "working_directory" field.
func (_u *SessionUpdate) ClearWorkingDirectory() *SessionUpdate {
	_u.mutation.ClearWorkingDirectory()
	return _u
}

// SetProjectName sets the "project_name" field.
func (_u *SessionUpdate) SetProjectName(v string) *SessionUpdate {
	_u.mutation.SetProjectName(v)
	return _u
}

// SetNillableProjectName sets the "project_name" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableProjectName(v *string) *SessionUpdate {
	if v != nil {
		_u.SetProjectName(*v)
	}
	return _u
}

// ClearProjectName clears the value of the "project_name" field.
func (_u *SessionUpdate) ClearProjectName() *SessionUpdate {
	_u.mutation.ClearProjectName()
	return _u
}

// SetTotalActions sets the "total_actions" field.
func (_u *SessionUpdate) SetTotalActions(v int) *SessionUpdate {
	_u.mutation.ResetTotalActions()
	_u.mutation.SetTotalActions(v)
	return _u
}

// SetNillableTotalActions sets the "total_actions" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableTotalActions(v *int) *SessionUpdate {
	if v != nil {
		_u.SetTotalActions(*v)
	}
	return _u
}

// AddTotalActions adds value to the "total_actions" field.
func (_u *SessionUpdate) AddTotalActions(v int) *SessionUpdate {
	_u.mutation.AddTotalActions(v)
	return _u
}

// SetFilesRead sets the "files_read" field.
func (_u *SessionUpdate) SetFilesRead(v int) *SessionUpdate {
	_u.mutation.ResetFilesRead()
	_u.mutation.SetFilesRead(v)
	return _u
}

// SetNillableFilesRead sets the "files_read" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableFilesRead(v *int) *SessionUpdate {
	if v != nil {
		_u.SetFilesRead(*v)
	}
	return _u
}

// AddFilesRead adds value to the "files_read" field.
func (_u *SessionUpdate) AddFilesRead(v int) *SessionUpdate {
	_u.mutation.AddFilesRead(v)
	return _u
}

// SetFilesWritten sets the "files_written" field.
func (_u *SessionUpdate) SetFilesWritten(v int) *SessionUpdate {
	_u.mutation.ResetFilesWritten()
	_u.mutation.SetFilesWritten(v)
	return _u
}

// SetNillableFilesWritten sets the "files_written" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableFilesWritten(v *int) *SessionUpdate {
	if v != nil {
		_u.SetFilesWritten(*v)
	}
	return _u
}

// AddFilesWritten adds value to the "files_written" field.
func (_u *SessionUpdate) AddFilesWritten(v int) *SessionUpdate {
	_u.mutation.AddFilesWritten(v)
	return _u
}

// SetCommandsExecuted sets the "commands_executed" field.
func (_u *SessionUpdate) SetCommandsExecuted(v int) *SessionUpdate {
	_u.mutation.ResetCommandsExecuted()
	_u.mutation.SetCommandsExecuted(v)
	return _u
}

// SetNillableCommandsExecuted sets the "commands_executed" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCommandsExecuted(v *int) *SessionUpdate {
	if v != nil {
		_u.SetCommandsExecuted(*v)
	}
	return _u
}

// AddCommandsExecuted adds value to the "commands_executed" field.
func (_u *SessionUpdate) AddCommandsExecuted(v int) *SessionUpdate {
	_u.mutation.AddCommandsExecuted(v)
	return _u
}

// SetErrors sets the "errors" field.
func (_u *SessionUpdate) SetErrors(v int) *SessionUpdate {
	_u.mutation.ResetErrors()
	_u.mutation.SetErrors(v)
	return _u
}

// SetNillableErrors sets the "errors" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableErrors(v *int) *SessionUpdate {
	if v != nil {
		_u.SetErrors(*v)
	}
	return _u
}

// AddErrors adds value to the "errors" field.
func (_u *SessionUpdate) AddErrors(v int) *SessionUpdate {
	_u.mutation.AddErrors(v)
	return _u
}

// SetSensitiveActions sets the "sensitive_actions" field.
func (_u *SessionUpdate) SetSensitiveActions(v int) *SessionUpdate {
	_u.mutation.ResetSensitiveActions()
	_u.mutation.SetSensitiveActions(v)
	return _u
}

// SetNillableSensitiveActions sets the "sensitive_actions" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableSensitiveActions(v *int) *SessionUpdate {
	if v != nil {
		_u.SetSensitiveActions(*v)
	}
	return _u
}

// AddSensitiveActions adds value to the "sensitive_actions" field.
func (_u *SessionUpdate) AddSensitiveActions(v int) *SessionUpdate {
	_u.mutation.AddSensitiveActions(v)
	return _u
}

// SetBlockedActions sets the "blocked_actions" field.
func (_u *SessionUpdate) SetBlockedActions(v int) *SessionUpdate {
	_u.mutation.ResetBlockedActions()
	_u.mutation.SetBlockedActions(v)
	return _u
}

// SetNillableBlockedActions sets the "blocked_actions" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableBlockedActions(v *int) *SessionUpdate {
	if v != nil {
		_u.SetBlockedActions(*v)
	}
	return _u
}

// AddBlockedActions adds value to the "blocked_actions" field.
func (_u *SessionUpdate) AddBlockedActions(v int) *SessionUpdate {
	_u.mutation.AddBlockedActions(v)
	return _u
}

// SetTranscriptPath sets the "transcript_path" field.
func (_u *SessionUpdate) SetTranscriptPath(v string) *SessionUpdate {
	_u.mutation.SetTranscriptPath(v)
	return _u
}

// SetNillableTranscriptPath sets the "transcript_path" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableTranscriptPath(v *string) *SessionUpdate {
	if v != nil {
		_u.SetTranscriptPath(*v)
	}
	return _u
}

// ClearTranscriptPath clears the value of the "transcript_path" field.
func (_u *SessionUpdate) ClearTranscriptPath() *SessionUpdate {
	_u.mutation.ClearTranscriptPath()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *SessionUpdate) SetInputTokens(v int64) *SessionUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableInputTokens(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *SessionUpdate) AddInputTokens(v int64) *SessionUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *SessionUpdate) SetOutputTokens(v int64) *SessionUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableOutputTokens(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *SessionUpdate) AddOutputTokens(v int64) *SessionUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *SessionUpdate) SetCacheReadTokens(v int64) *SessionUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCacheReadTokens(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *SessionUpdate) AddCacheReadTokens(v int64) *SessionUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheWriteTokens sets the "cache_write_tokens" field.
func (_u *SessionUpdate) SetCacheWriteTokens(v int64) *SessionUpdate {
	_u.mutation.ResetCacheWriteTokens()
	_u.mutation.SetCacheWriteTokens(v)
	return _u
}

// SetNillableCacheWriteTokens sets the "cache_write_tokens" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCacheWriteTokens(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetCacheWriteTokens(*v)
	}
	return _u
}

// AddCacheWriteTokens adds value to the "cache_write_tokens" field.
func (_u *SessionUpdate) AddCacheWriteTokens(v int64) *SessionUpdate {
	_u.mutation.AddCacheWriteTokens(v)
	return _u
}

// SetEstimatedCostUsd sets the "estimated_cost_usd" field.
func (_u *SessionUpdate) SetEstimatedCostUsd(v float64) *SessionUpdate {
	_u.mutation.ResetEstimatedCostUsd()
	_u.mutation.SetEstimatedCostUsd(v)
	return _u
}

// SetNillableEstimatedCostUsd sets the "estimated_cost_usd" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableEstimatedCostUsd(v *float64) *SessionUpdate {
	if v != nil {
		_u.SetEstimatedCostUsd(*v)
	}
	return _u
}

// AddEstimatedCostUsd adds value to the "estimated_cost_usd" field.
func (_u *SessionUpdate) AddEstimatedCostUsd(v float64) *SessionUpdate {
	_u.mutation.AddEstimatedCostUsd(v)
	return _u
}

// SetModelUsage sets the "model_usage" field.
func (_u *SessionUpdate) SetModelUsage(v []map[string]interface{}) *SessionUpdate {
	_u.mutation.SetModelUsage(v)
	return _u
}

// AppendModelUsage appends value to the "model_usage" field.
func (_u *SessionUpdate) AppendModelUsage(v []map[string]interface{}) *SessionUpdate {
	_u.mutation.AppendModelUsage(v)
	return _u
}

// ClearModelUsage clears the value of the "model_usage" field.
func (_u *SessionUpdate) ClearModelUsage() *SessionUpdate {
	_u.mutation.ClearModelUsage()
	return _u
}

// SetCostSource sets the "cost_source" field.
func (_u *SessionUpdate) SetCostSource(v string) *SessionUpdate {
	_u.mutation.SetCostSource(v)
	return _u
}

// SetNillableCostSource sets the "cost_source" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCostSource(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCostSource(*v)
	}
	return _u
}

// ClearCostSource clears the value of the "cost_source" field.
func (_u *SessionUpdate) ClearCostSource() *SessionUpdate {
	_u.mutation.ClearCostSource()
	return _u
}

// SetCostComputedAt sets the "cost_computed_at" field.
func (_u *SessionUpdate) SetCostComputedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetCostComputedAt(v)
	return _u
}

// SetNillableCostComputedAt sets the "cost_computed_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCostComputedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetCostComputedAt(*v)
	}
	return _u
}

// ClearCostComputedAt clears the value of the "cost_computed_at" field.
func (_u *SessionUpdate) ClearCostComputedAt() *SessionUpdate {
	_u.mutation.ClearCostComputedAt()
	return _u
}

// AddEventIDs adds the "events" edge to the AuditEvent entity by IDs.
func (_u *SessionUpdate) AddEventIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the AuditEvent entity.
func (_u *SessionUpdate) AddEvents(v ...*AuditEvent) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the AuditEvent entity.
func (_u *SessionUpdate) ClearEvents() *SessionUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to AuditEvent entities by IDs.
func (_u *SessionUpdate) RemoveEventIDs(ids ...uuid.UUID) *SessionUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to AuditEvent entities.
func (_u *SessionUpdate) RemoveEvents(v ...*AuditEvent) *SessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if v, ok := _u.mutation.AgentName(); ok {
		if err := session.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "Session.agent_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentSessionID(); ok {
		_spec.SetField(session.FieldAgentSessionID, field.TypeString, value)
	}
	if _u.mutation.AgentSessionIDCleared() {
		_spec.ClearField(session.FieldAgentSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentName(); ok {
		_spec.SetField(session.FieldAgentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentVersion(); ok {
		_spec.SetField(session.FieldAgentVersion, field.TypeString, value)
	}
	if _u.mutation.AgentVersionCleared() {
		_spec.ClearField(session.FieldAgentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkingDirectory(); ok {
		_spec.SetField(session.FieldWorkingDirectory, field.TypeString, value)
	}
	if _u.mutation.WorkingDirectoryCleared() {
		_spec.ClearField(session.FieldWorkingDirectory, field.TypeString)
	}
	if value, ok := _u.mutation.ProjectName(); ok {
		_spec.SetField(session.FieldProjectName, field.TypeString, value)
	}
	if _u.mutation.ProjectNameCleared() {
		_spec.ClearField(session.FieldProjectName, field.TypeString)
	}
	if value, ok := _u.mutation.TotalActions(); ok {
		_spec.SetField(session.FieldTotalActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalActions(); ok {
		_spec.AddField(session.FieldTotalActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesRead(); ok {
		_spec.SetField(session.FieldFilesRead, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesRead(); ok {
		_spec.AddField(session.FieldFilesRead, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesWritten(); ok {
		_spec.SetField(session.FieldFilesWritten, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesWritten(); ok {
		_spec.AddField(session.FieldFilesWritten, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommandsExecuted(); ok {
		_spec.SetField(session.FieldCommandsExecuted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommandsExecuted(); ok {
		_spec.AddField(session.FieldCommandsExecuted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(session.FieldErrors, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrors(); ok {
		_spec.AddField(session.FieldErrors, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SensitiveActions(); ok {
		_spec.SetField(session.FieldSensitiveActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSensitiveActions(); ok {
		_spec.AddField(session.FieldSensitiveActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BlockedActions(); ok {
		_spec.SetField(session.FieldBlockedActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBlockedActions(); ok {
		_spec.AddField(session.FieldBlockedActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TranscriptPath(); ok {
		_spec.SetField(session.FieldTranscriptPath, field.TypeString, value)
	}
	if _u.mutation.TranscriptPathCleared() {
		_spec.ClearField(session.FieldTranscriptPath, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(session.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(session.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(session.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(session.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(session.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(session.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWriteTokens(); ok {
		_spec.SetField(session.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWriteTokens(); ok {
		_spec.AddField(session.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EstimatedCostUsd(); ok {
		_spec.SetField(session.FieldEstimatedCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCostUsd(); ok {
		_spec.AddField(session.FieldEstimatedCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ModelUsage(); ok {
		_spec.SetField(session.FieldModelUsage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelUsage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldModelUsage, value)
		})
	}
	if _u.mutation.ModelUsageCleared() {
		_spec.ClearField(session.FieldModelUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.CostSource(); ok {
		_spec.SetField(session.FieldCostSource, field.TypeString, value)
	}
	if _u.mutation.CostSourceCleared() {
		_spec.ClearField(session.FieldCostSource, field.TypeString)
	}
	if value, ok := _u.mutation.CostComputedAt(); ok {
		_spec.SetField(session.FieldCostComputedAt, field.TypeTime, value)
	}
	if _u.mutation.CostComputedAtCleared() {
		_spec.ClearField(session.FieldCostComputedAt, field.TypeTime)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.EventsTable,
			Columns: []string{session.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.EventsTable,
			Columns: []string{session.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.EventsTable,
			Columns: []string{session.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetAgentSessionID sets the "agent_session_id" field.
func (_u *SessionUpdateOne) SetAgentSessionID(v string) *SessionUpdateOne {
	_u.mutation.SetAgentSessionID(v)
	return _u
}

// SetNillableAgentSessionID sets the "agent_session_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableAgentSessionID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetAgentSessionID(*v)
	}
	return _u
}

// ClearAgentSessionID clears the value of the "agent_session_id" field.
func (_u *SessionUpdateOne) ClearAgentSessionID() *SessionUpdateOne {
	_u.mutation.ClearAgentSessionID()
	return _u
}

// SetAgentName sets the "agent_name" field.
func (_u *SessionUpdateOne) SetAgentName(v string) *SessionUpdateOne {
	_u.mutation.SetAgentName(v)
	return _u
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableAgentName(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetAgentName(*v)
	}
	return _u
}

// SetAgentVersion sets the "agent_version" field.
func (_u *SessionUpdateOne) SetAgentVersion(v string) *SessionUpdateOne {
	_u.mutation.SetAgentVersion(v)
	return _u
}

// SetNillableAgentVersion sets the "agent_version" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableAgentVersion(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetAgentVersion(*v)
	}
	return _u
}

// ClearAgentVersion clears the value of the "agent_version" field.
func (_u *SessionUpdateOne) ClearAgentVersion() *SessionUpdateOne {
	_u.mutation.ClearAgentVersion()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SessionUpdateOne) SetEndedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEndedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SessionUpdateOne) ClearEndedAt() *SessionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetWorkingDirectory sets the "working_directory" field.
func (_u *SessionUpdateOne) SetWorkingDirectory(v string) *SessionUpdateOne {
	_u.mutation.SetWorkingDirectory(v)
	return _u
}

// SetNillableWorkingDirectory sets the "working_directory" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableWorkingDirectory(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetWorkingDirectory(*v)
	}
	return _u
}

// ClearWorkingDirectory clears the value of the "working_directory" field.
func (_u *SessionUpdateOne) ClearWorkingDirectory() *SessionUpdateOne {
	_u.mutation.ClearWorkingDirectory()
	return _u
}

// SetProjectName sets the "project_name" field.
func (_u *SessionUpdateOne) SetProjectName(v string) *SessionUpdateOne {
	_u.mutation.SetProjectName(v)
	return _u
}

// SetNillableProjectName sets the "project_name" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableProjectName(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetProjectName(*v)
	}
	return _u
}

// ClearProjectName clears the value of the "project_name" field.
func (_u *SessionUpdateOne) ClearProjectName() *SessionUpdateOne {
	_u.mutation.ClearProjectName()
	return _u
}

// SetTotalActions sets the "total_actions" field.
func (_u *SessionUpdateOne) SetTotalActions(v int) *SessionUpdateOne {
	_u.mutation.ResetTotalActions()
	_u.mutation.SetTotalActions(v)
	return _u
}

// SetNillableTotalActions sets the "total_actions" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableTotalActions(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetTotalActions(*v)
	}
	return _u
}

// AddTotalActions adds value to the "total_actions" field.
func (_u *SessionUpdateOne) AddTotalActions(v int) *SessionUpdateOne {
	_u.mutation.AddTotalActions(v)
	return _u
}

// SetFilesRead sets the "files_read" field.
func (_u *SessionUpdateOne) SetFilesRead(v int) *SessionUpdateOne {
	_u.mutation.ResetFilesRead()
	_u.mutation.SetFilesRead(v)
	return _u
}

// SetNillableFilesRead sets the "files_read" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableFilesRead(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetFilesRead(*v)
	}
	return _u
}

// AddFilesRead adds value to the "files_read" field.
func (_u *SessionUpdateOne) AddFilesRead(v int) *SessionUpdateOne {
	_u.mutation.AddFilesRead(v)
	return _u
}

// SetFilesWritten sets the "files_written" field.
func (_u *SessionUpdateOne) SetFilesWritten(v int) *SessionUpdateOne {
	_u.mutation.ResetFilesWritten()
	_u.mutation.SetFilesWritten(v)
	return _u
}

// SetNillableFilesWritten sets the "files_written" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableFilesWritten(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetFilesWritten(*v)
	}
	return _u
}

// AddFilesWritten adds value to the "files_written" field.
func (_u *SessionUpdateOne) AddFilesWritten(v int) *SessionUpdateOne {
	_u.mutation.AddFilesWritten(v)
	return _u
}

// SetCommandsExecuted sets the "commands_executed" field.
func (_u *SessionUpdateOne) SetCommandsExecuted(v int) *SessionUpdateOne {
	_u.mutation.ResetCommandsExecuted()
	_u.mutation.SetCommandsExecuted(v)
	return _u
}

// SetNillableCommandsExecuted sets the "commands_executed" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCommandsExecuted(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetCommandsExecuted(*v)
	}
	return _u
}

// AddCommandsExecuted adds value to the "commands_executed" field.
func (_u *SessionUpdateOne) AddCommandsExecuted(v int) *SessionUpdateOne {
	_u.mutation.AddCommandsExecuted(v)
	return _u
}

// SetErrors sets the "errors" field.
func (_u *SessionUpdateOne) SetErrors(v int) *SessionUpdateOne {
	_u.mutation.ResetErrors()
	_u.mutation.SetErrors(v)
	return _u
}

// SetNillableErrors sets the "errors" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableErrors(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetErrors(*v)
	}
	return _u
}

// AddErrors adds value to the "errors" field.
func (_u *SessionUpdateOne) AddErrors(v int) *SessionUpdateOne {
	_u.mutation.AddErrors(v)
	return _u
}

// SetSensitiveActions sets the "sensitive_actions" field.
func (_u *SessionUpdateOne) SetSensitiveActions(v int) *SessionUpdateOne {
	_u.mutation.ResetSensitiveActions()
	_u.mutation.SetSensitiveActions(v)
	return _u
}

// SetNillableSensitiveActions sets the "sensitive_actions" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableSensitiveActions(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetSensitiveActions(*v)
	}
	return _u
}

// AddSensitiveActions adds value to the "sensitive_actions" field.
func (_u *SessionUpdateOne) AddSensitiveActions(v int) *SessionUpdateOne {
	_u.mutation.AddSensitiveActions(v)
	return _u
}

// SetBlockedActions sets the "blocked_actions" field.
func (_u *SessionUpdateOne) SetBlockedActions(v int) *SessionUpdateOne {
	_u.mutation.ResetBlockedActions()
	_u.mutation.SetBlockedActions(v)
	return _u
}

// SetNillableBlockedActions sets the "blocked_actions" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableBlockedActions(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetBlockedActions(*v)
	}
	return _u
}

// AddBlockedActions adds value to the "blocked_actions" field.
func (_u *SessionUpdateOne) AddBlockedActions(v int) *SessionUpdateOne {
	_u.mutation.AddBlockedActions(v)
	return _u
}

// SetTranscriptPath sets the "transcript_path" field.
func (_u *SessionUpdateOne) SetTranscriptPath(v string) *SessionUpdateOne {
	_u.mutation.SetTranscriptPath(v)
	return _u
}

// SetNillableTranscriptPath sets the "transcript_path" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableTranscriptPath(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetTranscriptPath(*v)
	}
	return _u
}

// ClearTranscriptPath clears the value of the "transcript_path" field.
func (_u *SessionUpdateOne) ClearTranscriptPath() *SessionUpdateOne {
	_u.mutation.ClearTranscriptPath()
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *SessionUpdateOne) SetInputTokens(v int64) *SessionUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableInputTokens(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *SessionUpdateOne) AddInputTokens(v int64) *SessionUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *SessionUpdateOne) SetOutputTokens(v int64) *SessionUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableOutputTokens(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *SessionUpdateOne) AddOutputTokens(v int64) *SessionUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *SessionUpdateOne) SetCacheReadTokens(v int64) *SessionUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCacheReadTokens(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *SessionUpdateOne) AddCacheReadTokens(v int64) *SessionUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheWriteTokens sets the "cache_write_tokens" field.
func (_u *SessionUpdateOne) SetCacheWriteTokens(v int64) *SessionUpdateOne {
	_u.mutation.ResetCacheWriteTokens()
	_u.mutation.SetCacheWriteTokens(v)
	return _u
}

// SetNillableCacheWriteTokens sets the "cache_write_tokens" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCacheWriteTokens(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetCacheWriteTokens(*v)
	}
	return _u
}

// AddCacheWriteTokens adds value to the "cache_write_tokens" field.
func (_u *SessionUpdateOne) AddCacheWriteTokens(v int64) *SessionUpdateOne {
	_u.mutation.AddCacheWriteTokens(v)
	return _u
}

// SetEstimatedCostUsd sets the "estimated_cost_usd" field.
func (_u *SessionUpdateOne) SetEstimatedCostUsd(v float64) *SessionUpdateOne {
	_u.mutation.ResetEstimatedCostUsd()
	_u.mutation.SetEstimatedCostUsd(v)
	return _u
}

// SetNillableEstimatedCostUsd sets the "estimated_cost_usd" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableEstimatedCostUsd(v *float64) *SessionUpdateOne {
	if v != nil {
		_u.SetEstimatedCostUsd(*v)
	}
	return _u
}

// AddEstimatedCostUsd adds value to the "estimated_cost_usd" field.
func (_u *SessionUpdateOne) AddEstimatedCostUsd(v float64) *SessionUpdateOne {
	_u.mutation.AddEstimatedCostUsd(v)
	return _u
}

// SetModelUsage sets the "model_usage" field.
func (_u *SessionUpdateOne) SetModelUsage(v []map[string]interface{}) *SessionUpdateOne {
	_u.mutation.SetModelUsage(v)
	return _u
}

// AppendModelUsage appends value to the "model_usage" field.
func (_u *SessionUpdateOne) AppendModelUsage(v []map[string]interface{}) *SessionUpdateOne {
	_u.mutation.AppendModelUsage(v)
	return _u
}

// ClearModelUsage clears the value of the "model_usage" field.
func (_u *SessionUpdateOne) ClearModelUsage() *SessionUpdateOne {
	_u.mutation.ClearModelUsage()
	return _u
}

// SetCostSource sets the "cost_source" field.
func (_u *SessionUpdateOne) SetCostSource(v string) *SessionUpdateOne {
	_u.mutation.SetCostSource(v)
	return _u
}

// SetNillableCostSource sets the "cost_source" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCostSource(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCostSource(*v)
	}
	return _u
}

// ClearCostSource clears the value of the "cost_source" field.
func (_u *SessionUpdateOne) ClearCostSource() *SessionUpdateOne {
	_u.mutation.ClearCostSource()
	return _u
}

// SetCostComputedAt sets the "cost_computed_at" field.
func (_u *SessionUpdateOne) SetCostComputedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetCostComputedAt(v)
	return _u
}

// SetNillableCostComputedAt sets the "cost_computed_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCostComputedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetCostComputedAt(*v)
	}
	return _u
}

// ClearCostComputedAt clears the value of the "cost_computed_at" field.
func (_u *SessionUpdateOne) ClearCostComputedAt() *SessionUpdateOne {
	_u.mutation.ClearCostComputedAt()
	return _u
}

// AddEventIDs adds the "events" edge to the AuditEvent entity by IDs.
func (_u *SessionUpdateOne) AddEventIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the AuditEvent entity.
func (_u *SessionUpdateOne) AddEvents(v ...*AuditEvent) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the AuditEvent entity.
func (_u *SessionUpdateOne) ClearEvents() *SessionUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to AuditEvent entities by IDs.
func (_u *SessionUpdateOne) RemoveEventIDs(ids ...uuid.UUID) *SessionUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to AuditEvent entities.
func (_u *SessionUpdateOne) RemoveEvents(v ...*AuditEvent) *SessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if v, ok := _u.mutation.AgentName(); ok {
		if err := session.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "Session.agent_name": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentSessionID(); ok {
		_spec.SetField(session.FieldAgentSessionID, field.TypeString, value)
	}
	if _u.mutation.AgentSessionIDCleared() {
		_spec.ClearField(session.FieldAgentSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.AgentName(); ok {
		_spec.SetField(session.FieldAgentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentVersion(); ok {
		_spec.SetField(session.FieldAgentVersion, field.TypeString, value)
	}
	if _u.mutation.AgentVersionCleared() {
		_spec.ClearField(session.FieldAgentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(session.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(session.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkingDirectory(); ok {
		_spec.SetField(session.FieldWorkingDirectory, field.TypeString, value)
	}
	if _u.mutation.WorkingDirectoryCleared() {
		_spec.ClearField(session.FieldWorkingDirectory, field.TypeString)
	}
	if value, ok := _u.mutation.ProjectName(); ok {
		_spec.SetField(session.FieldProjectName, field.TypeString, value)
	}
	if _u.mutation.ProjectNameCleared() {
		_spec.ClearField(session.FieldProjectName, field.TypeString)
	}
	if value, ok := _u.mutation.TotalActions(); ok {
		_spec.SetField(session.FieldTotalActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalActions(); ok {
		_spec.AddField(session.FieldTotalActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesRead(); ok {
		_spec.SetField(session.FieldFilesRead, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesRead(); ok {
		_spec.AddField(session.FieldFilesRead, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FilesWritten(); ok {
		_spec.SetField(session.FieldFilesWritten, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFilesWritten(); ok {
		_spec.AddField(session.FieldFilesWritten, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommandsExecuted(); ok {
		_spec.SetField(session.FieldCommandsExecuted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommandsExecuted(); ok {
		_spec.AddField(session.FieldCommandsExecuted, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Errors(); ok {
		_spec.SetField(session.FieldErrors, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrors(); ok {
		_spec.AddField(session.FieldErrors, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SensitiveActions(); ok {
		_spec.SetField(session.FieldSensitiveActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSensitiveActions(); ok {
		_spec.AddField(session.FieldSensitiveActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BlockedActions(); ok {
		_spec.SetField(session.FieldBlockedActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBlockedActions(); ok {
		_spec.AddField(session.FieldBlockedActions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TranscriptPath(); ok {
		_spec.SetField(session.FieldTranscriptPath, field.TypeString, value)
	}
	if _u.mutation.TranscriptPathCleared() {
		_spec.ClearField(session.FieldTranscriptPath, field.TypeString)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(session.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(session.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(session.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(session.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(session.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(session.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWriteTokens(); ok {
		_spec.SetField(session.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWriteTokens(); ok {
		_spec.AddField(session.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EstimatedCostUsd(); ok {
		_spec.SetField(session.FieldEstimatedCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCostUsd(); ok {
		_spec.AddField(session.FieldEstimatedCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ModelUsage(); ok {
		_spec.SetField(session.FieldModelUsage, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelUsage(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, session.FieldModelUsage, value)
		})
	}
	if _u.mutation.ModelUsageCleared() {
		_spec.ClearField(session.FieldModelUsage, field.TypeJSON)
	}
	if value, ok := _u.mutation.CostSource(); ok {
		_spec.SetField(session.FieldCostSource, field.TypeString, value)
	}
	if _u.mutation.CostSourceCleared() {
		_spec.ClearField(session.FieldCostSource, field.TypeString)
	}
	if value, ok := _u.mutation.CostComputedAt(); ok {
		_spec.SetField(session.FieldCostComputedAt, field.TypeTime, value)
	}
	if _u.mutation.CostComputedAtCleared() {
		_spec.ClearField(session.FieldCostComputedAt, field.TypeTime)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.EventsTable,
			Columns: []string{session.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.EventsTable,
			Columns: []string{session.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   session.EventsTable,
			Columns: []string{session.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
