// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/gryph/storage/ent/predicate"
	"github.com/safedep/gryph/storage/ent/streamcheckpoint"
)

// StreamCheckpointDelete is the builder for deleting a StreamCheckpoint entity.
type StreamCheckpointDelete struct {
	config
	hooks    []Hook
	mutation *StreamCheckpointMutation
}

// Where appends a list predicates to the StreamCheckpointDelete builder.
func (_d *StreamCheckpointDelete) Where(ps ...predicate.StreamCheckpoint) *StreamCheckpointDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StreamCheckpointDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StreamCheckpointDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StreamCheckpointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(streamcheckpoint.Table, sqlgraph.NewFieldSpec(streamcheckpoint.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StreamCheckpointDeleteOne is the builder for deleting a single StreamCheckpoint entity.
type StreamCheckpointDeleteOne struct {
	_d *StreamCheckpointDelete
}

// Where appends a list predicates to the StreamCheckpointDelete builder.
func (_d *StreamCheckpointDeleteOne) Where(ps ...predicate.StreamCheckpoint) *StreamCheckpointDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StreamCheckpointDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{streamcheckpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StreamCheckpointDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
